'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {context,validKey,requestDigest,containsSecret,provenanceErrors,canTransition,canApprove,deliveryState}=require('../policy');
const runtimeRoot=path.resolve(__dirname,'..','..');let projectRoot=runtimeRoot;while(!fs.existsSync(path.join(projectRoot,'start.sh'))){const parent=path.dirname(projectRoot);if(parent===projectRoot)throw new Error('project root not found');projectRoot=parent;}
test('authorization requires signed tenant and subject scope',()=>{assert.equal(context({sub:'u',role:'admin'}),null);assert.deepEqual(context({sub:'u',tenantId:'t-1',role:'reviewer',subjectIds:['s-1']}),{actor:'u',tenant:'t-1',role:'reviewer',subjects:['s-1']});assert.equal(canApprove({actor:'u',creator:'u',role:'reviewer',status:'submitted',roles:['reviewer']}),false);});
test('contracts reject weak keys, secrets and incomplete provenance',()=>{assert.equal(validKey('workflow:0001'),true);assert.equal(validKey('short'),false);assert.equal(containsSecret({privateKey:'x'}),true);assert.deepEqual(provenanceErrors([{sourceRef:'doc:1',rightsBasis:'owned',capturedAt:'2026-07-18T00:00:00Z'}]),[]);});
test('idempotency digest is canonical and payload-bound',()=>{assert.equal(requestDigest({b:2,a:1}),requestDigest({a:1,b:2}));assert.notEqual(requestDigest({operation:'export'}),requestDigest({operation:'delete'}));});
test('retry policy reaches dead letter deterministically',()=>{assert.equal(deliveryState('failed',0),'failed');assert.equal(deliveryState('failed',4),'dead_letter');assert.equal(deliveryState('delivered',2),'delivered');});
test('state machine denies approval and erasure shortcuts',()=>{assert.equal(canTransition('draft','submitted'),true);assert.equal(canTransition('submitted','approved'),true);assert.equal(canTransition('draft','approved'),false);assert.equal(canTransition('erased','draft'),false);});
test('additive schema enforces tenant keys, immutable audit and leases',()=>{const sql=fs.readFileSync(path.join(runtimeRoot,'migrations','001_governed_workflows.sql'),'utf8');assert.match(sql,/FOREIGN KEY\(tenant_id,work_item_id\)/);assert.match(sql,/append_only/);assert.match(sql,/request_hash CHAR\(64\) NOT NULL/);assert.match(sql,/lease_expires_at/);assert.match(sql,/connector_checkpoints/);});
test('router atomically records decisions and quarantines providers',()=>{const source=fs.readFileSync(path.join(runtimeRoot,'governance','router.js'),'utf8');assert.match(source,/WITH changed AS/);assert.match(source,/created_by<>\$2/);assert.match(source,/FOR UPDATE SKIP LOCKED/);assert.match(source,/X-Claim-Token/);assert.match(source,/provider_receipt/);assert.match(source,/Idempotency-Key was already used/);});
test('host mount and lifecycle are fail closed and non-destructive',()=>{const host=fs.readFileSync(path.join(runtimeRoot,"src/index.ts"),'utf8');const launcher=fs.readFileSync(path.join(projectRoot,'start.sh'),'utf8');assert.match(host,/governanceRouter|governance\W/);assert.match(host,/\/api\/governance/);assert.match(host,/ENABLE_GENERATED_FEATURES/);assert.doesNotMatch(launcher,/kill\s+-9|npm install|db push|createdb|brew services|seed_database/);assert.match(launcher,/ALLOW_SCHEMA_MIGRATION/);});
test('configuration and operations require explicit secrets and tenant',()=>{const env=fs.readFileSync(path.join(projectRoot,'.env.example'),'utf8');const runbook=fs.readFileSync(path.join(projectRoot,'RUNBOOK.md'),'utf8');assert.match(env,/^JWT_SECRET=$/m);assert.match(env,/^DATABASE_URL=$/m);assert.match(env,/^GOVERNANCE_TENANT_ID=$/m);assert.match(runbook,/rollback/i);assert.match(runbook,/dead.?letter/i);assert.match(runbook,/retention/i);});
test('delivery evidence is typed and secret free',()=>{const source=fs.readFileSync(path.join(runtimeRoot,'governance','router.js'),'utf8');assert.match(source,/receiptRef and receivedAt/);assert.match(source,/containsSecret\(req\.body\.receipt\)/);assert.match(source,/bounded failure errorCode required/);assert.doesNotMatch(source,/req\.body\.error\b/);});

