import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(__dirname, '../../../.env') });

import sequelize from '../config/database';
import {
  User,
  Script,
  Title,
  Description,
  Hashtag,
  Thumbnail,
  Hook,
  Calendar,
  Trend,
  Comment,
  Idea,
  Seo,
  Analytics,
  Competitor,
  Persona,
  Repurpose,
} from '../models';

const seedDatabase = async () => {
  try {
    console.log('🌱 Starting database seeding...');

    // Sync database (force: true will drop and recreate tables)
    await sequelize.sync({ force: true });
    console.log('✅ Database synchronized');

    // Create demo user
    const demoUser = await User.create({
      email: 'demo@creator.ai',
      password: 'demo123',
      name: 'Demo Creator',
    });
    console.log('✅ Demo user created');

    const userId = demoUser.id;

    // Seed Scripts (15+ items)
    const scriptsData = [
      { title: 'Morning Routine Vlog', topic: 'My productive morning routine as a content creator', platform: 'YouTube', duration: '10 minutes', tone: 'Casual and relatable', aiOutput: '**Video Script: Morning Routine**\n\n[INTRO - 0:00]\nHook: "What if waking up at 5 AM actually changed your life?"\n\n[MAIN CONTENT]\n1. Wake up routine\n2. Meditation practice\n3. Content planning session\n4. Breakfast and journaling\n\n[OUTRO]\nCTA: Subscribe for more productivity tips!' },
      { title: 'Tech Review: iPhone 15', topic: 'Comprehensive review of the new iPhone 15 Pro Max', platform: 'YouTube', duration: '15 minutes', tone: 'Professional and informative', aiOutput: '**Tech Review Script**\n\n[INTRO]\nHook: "Is this the best iPhone ever made?"\n\n[SECTIONS]\n1. Unboxing experience\n2. Design and build quality\n3. Camera deep dive\n4. Performance benchmarks\n5. Battery life test\n\n[CONCLUSION]\nFinal verdict and recommendations' },
      { title: 'Travel Vlog: Tokyo', topic: 'First time in Tokyo - hidden gems and local food', platform: 'YouTube', duration: '20 minutes', tone: 'Adventurous and excited', aiOutput: '**Tokyo Travel Vlog**\n\n[DAY 1]\n- Arrival and first impressions\n- Shibuya crossing experience\n- Late night ramen hunt\n\n[DAY 2]\n- Hidden temples\n- Local market exploration\n- Street food tour' },
      { title: 'Cooking Tutorial: Pasta', topic: 'How to make restaurant-quality pasta at home', platform: 'YouTube', duration: '12 minutes', tone: 'Friendly and instructional', aiOutput: '**Pasta Tutorial Script**\n\n[INGREDIENTS]\nList all ingredients with measurements\n\n[STEPS]\n1. Making fresh pasta dough\n2. Rolling and cutting\n3. Sauce preparation\n4. Final assembly\n\n[TIPS]\nPro tips for perfect pasta every time' },
      { title: 'Fitness Challenge', topic: '30-day fitness transformation challenge', platform: 'TikTok', duration: '60 seconds', tone: 'Motivational and energetic', aiOutput: '**Fitness Challenge Hook**\n\nDay 1: "I\'m starting a 30-day challenge..."\n\nDay 15: Progress update with metrics\n\nDay 30: Final transformation reveal\n\nCTA: Join the challenge!' },
      { title: 'Study With Me', topic: 'Real-time study session for productivity', platform: 'YouTube', duration: '2 hours', tone: 'Calm and focused', aiOutput: '**Study Session Format**\n\n[INTRO - 2 min]\nSession goals and timer setup\n\n[POMODORO SESSIONS]\n4x 25-minute focus blocks\n5-minute breaks between\n\n[OUTRO]\nSession recap and encouragement' },
      { title: 'Gaming Stream Highlights', topic: 'Best moments from recent gaming streams', platform: 'YouTube', duration: '8 minutes', tone: 'Fun and entertaining', aiOutput: '**Gaming Highlights Script**\n\n[INTRO]\nQuick montage of epic moments\n\n[CLIPS]\n1. Clutch plays\n2. Funny fails\n3. Chat interactions\n4. Victory moments\n\n[OUTRO]\nStream schedule and subscribe reminder' },
      { title: 'Budget Tips', topic: 'How I save $500 every month', platform: 'TikTok', duration: '90 seconds', tone: 'Practical and helpful', aiOutput: '**Money Saving Tips**\n\nTip 1: Track every expense\nTip 2: 50/30/20 budget rule\nTip 3: Cancel unused subscriptions\nTip 4: Meal prep Sundays\nTip 5: No-spend weekends\n\nTotal savings: $500/month!' },
      { title: 'Room Tour 2024', topic: 'Complete tour of my content creation setup', platform: 'YouTube', duration: '18 minutes', tone: 'Excited and detailed', aiOutput: '**Room Tour Script**\n\n[INTRO]\nOverview of the space\n\n[SECTIONS]\n1. Desk setup and monitors\n2. Camera and lighting gear\n3. Audio equipment\n4. Storage and organization\n5. Comfort items\n\n[TOTAL COST]\nBreakdown of investment' },
      { title: 'Day in My Life', topic: 'Realistic day as a full-time content creator', platform: 'YouTube', duration: '15 minutes', tone: 'Authentic and relatable', aiOutput: '**Day in My Life Vlog**\n\n[MORNING]\n6:00 AM - Wake up\n7:00 AM - Content planning\n8:00 AM - Filming\n\n[AFTERNOON]\n12:00 PM - Editing\n3:00 PM - Social media\n\n[EVENING]\nWind down routine' },
      { title: 'Q&A Video', topic: 'Answering your most asked questions', platform: 'YouTube', duration: '25 minutes', tone: 'Personal and engaging', aiOutput: '**Q&A Script**\n\n[INTRO]\nThank fans for questions\n\n[QUESTIONS]\n1. How did you start?\n2. What camera do you use?\n3. How do you stay motivated?\n4. Advice for beginners?\n5. Future plans?\n\n[OUTRO]\nSubmit more questions for next time' },
      { title: 'Storytime: My Journey', topic: 'How I became a full-time content creator', platform: 'YouTube', duration: '22 minutes', tone: 'Inspiring and honest', aiOutput: '**Storytime Script**\n\n[BEGINNING]\nLife before content creation\n\n[TURNING POINT]\nThe moment everything changed\n\n[STRUGGLES]\nChallenges and failures\n\n[SUCCESS]\nBreakthrough moments\n\n[LESSONS]\nWhat I learned along the way' },
      { title: 'Product Haul', topic: 'Amazon favorites under $50', platform: 'TikTok', duration: '3 minutes', tone: 'Enthusiastic and honest', aiOutput: '**Product Haul Script**\n\n[INTRO]\n"These Amazon finds changed my life"\n\n[PRODUCTS]\n1. LED lights - $15\n2. Desk organizer - $20\n3. Ring light - $30\n4. Microphone - $45\n5. Tripod - $25\n\n[LINKS]\nAll links in bio!' },
      { title: 'Behind the Scenes', topic: 'What filming a video really looks like', platform: 'YouTube', duration: '10 minutes', tone: 'Raw and authentic', aiOutput: '**BTS Script**\n\n[PRE-PRODUCTION]\nResearch and scripting\n\n[PRODUCTION]\nActual filming process\nBloopers and retakes\n\n[POST-PRODUCTION]\nEditing workflow\nThumbnail creation\n\n[REALITY]\nThe parts nobody shows' },
      { title: 'Reaction Video', topic: 'Reacting to viral videos in my niche', platform: 'YouTube', duration: '12 minutes', tone: 'Entertaining and insightful', aiOutput: '**Reaction Video Script**\n\n[INTRO]\nWhat we\'re watching today\n\n[REACTIONS]\nVideo 1: Commentary\nVideo 2: Analysis\nVideo 3: Thoughts\n\n[DISCUSSION]\nKey takeaways and lessons' },
      { title: 'Tutorial: Video Editing', topic: 'Complete guide to editing videos for beginners', platform: 'YouTube', duration: '30 minutes', tone: 'Educational and patient', aiOutput: '**Editing Tutorial Script**\n\n[BASICS]\n1. Software overview\n2. Importing footage\n3. Timeline basics\n\n[INTERMEDIATE]\n4. Cuts and transitions\n5. Color correction\n6. Audio editing\n\n[ADVANCED]\n7. Effects and graphics\n8. Export settings' },
    ];

    await Script.bulkCreate(scriptsData.map(item => ({ ...item, userId })));
    console.log('✅ Scripts seeded');

    // Seed Titles (15+ items)
    const titlesData = [
      { topic: 'Morning routine productivity', platform: 'YouTube', style: 'Clickbait', keywords: 'morning routine, productivity, wake up early', aiOutput: '1. "I Woke Up at 5 AM for 30 Days - Here\'s What Happened"\n2. "The Morning Routine That Changed EVERYTHING"\n3. "Why Successful People Wake Up at 5 AM (The Truth)"\n4. "My $0 Morning Routine That Made Me Productive"\n5. "Stop Waking Up Like This (Do This Instead)"' },
      { topic: 'iPhone 15 review', platform: 'YouTube', style: 'Professional', keywords: 'iPhone 15, tech review, Apple', aiOutput: '1. "iPhone 15 Pro Max: 30 Days Later - Honest Review"\n2. "iPhone 15: Everything You Need to Know Before Buying"\n3. "Is iPhone 15 Worth the Upgrade? Complete Analysis"\n4. "iPhone 15 vs 14 Pro: The Definitive Comparison"\n5. "5 Things Nobody Tells You About iPhone 15"' },
      { topic: 'Budget travel tips', platform: 'TikTok', style: 'Casual', keywords: 'travel, budget, tips', aiOutput: '1. "How I Travel for FREE (Real Tips)"\n2. "Travel Hack That Saved Me $1000"\n3. "Stop Wasting Money on Travel"\n4. "POV: You Learned This Travel Hack"\n5. "Rich People Don\'t Want You to Know This"' },
      { topic: 'Home workout routine', platform: 'YouTube', style: 'Motivational', keywords: 'workout, fitness, home exercise', aiOutput: '1. "Get Fit in 30 Days - No Gym Required"\n2. "The Only Home Workout You\'ll Ever Need"\n3. "I Did 100 Push-ups Every Day for a Month"\n4. "Transform Your Body at Home (Free Workout)"\n5. "No Excuses: 20-Minute Full Body Workout"' },
      { topic: 'Cooking pasta', platform: 'YouTube', style: 'Educational', keywords: 'cooking, pasta, Italian food', aiOutput: '1. "Restaurant Chefs Don\'t Want You to See This"\n2. "The Perfect Pasta in Under 15 Minutes"\n3. "Why Your Pasta Tastes Wrong (Fix This)"\n4. "Italian Grandma Teaches Me Real Pasta"\n5. "Michelin Star Pasta at Home"' },
      { topic: 'Makeup tutorial', platform: 'TikTok', style: 'Trendy', keywords: 'makeup, beauty, tutorial', aiOutput: '1. "5-Minute Makeup That Looks Professional"\n2. "This Drugstore Product Changed My Life"\n3. "POV: You Finally Found the Perfect Foundation"\n4. "Makeup Artists HATE This Trick"\n5. "Get Ready With Me: Date Night Edition"' },
      { topic: 'Study tips', platform: 'YouTube', style: 'Helpful', keywords: 'study, productivity, students', aiOutput: '1. "How I Studied Less and Got Better Grades"\n2. "The Study Method That Changed My Life"\n3. "Stop Making These Study Mistakes"\n4. "Study With Me: 3 Hour Session"\n5. "How to Remember Everything You Study"' },
      { topic: 'Gaming setup', platform: 'YouTube', style: 'Enthusiastic', keywords: 'gaming, setup, PC', aiOutput: '1. "My Dream Gaming Setup Tour 2024"\n2. "Building the Ultimate Gaming PC on a Budget"\n3. "This $500 Setup Beats $5000 Builds"\n4. "Gaming Setup Makeover: Before vs After"\n5. "5 Must-Have Gaming Accessories"' },
      { topic: 'Fashion haul', platform: 'TikTok', style: 'Fun', keywords: 'fashion, haul, clothing', aiOutput: '1. "SHEIN Haul: Was It Worth It?"\n2. "I Spent $100 at Zara - Here\'s What I Got"\n3. "Building a Capsule Wardrobe"\n4. "Outfit Ideas for Every Occasion"\n5. "These Clothes Changed My Style"' },
      { topic: 'Money saving tips', platform: 'YouTube', style: 'Practical', keywords: 'money, saving, finance', aiOutput: '1. "How I Save $1000 Every Month"\n2. "Financial Habits of Millionaires"\n3. "Stop Being Broke: Do This Instead"\n4. "The 50/30/20 Rule Explained"\n5. "I Tried Living on $50 for a Week"' },
      { topic: 'Coffee recipes', platform: 'TikTok', style: 'Aesthetic', keywords: 'coffee, recipes, drinks', aiOutput: '1. "Starbucks Baristas Don\'t Want You to Know"\n2. "Make Cafe-Quality Coffee at Home"\n3. "This Iced Coffee Recipe Went Viral"\n4. "5 Coffee Recipes You Need to Try"\n5. "The Perfect Morning Coffee Ritual"' },
      { topic: 'Pet content', platform: 'YouTube', style: 'Cute', keywords: 'pets, dogs, cats', aiOutput: '1. "My Dog\'s Morning Routine"\n2. "Things Only Pet Owners Understand"\n3. "Testing Viral Pet Products on My Cat"\n4. "A Day in My Pet\'s Life"\n5. "My Pet\'s Reaction to [Trend]"' },
      { topic: 'Life advice', platform: 'YouTube', style: 'Inspirational', keywords: 'advice, life, motivation', aiOutput: '1. "What I Wish I Knew at 20"\n2. "Life Advice That Actually Works"\n3. "Things Nobody Tells You About Adulthood"\n4. "How to Stop Caring What People Think"\n5. "The Truth About Success Nobody Shares"' },
      { topic: 'DIY projects', platform: 'YouTube', style: 'Creative', keywords: 'DIY, crafts, projects', aiOutput: '1. "Amazing DIY Projects Under $20"\n2. "Transform Your Room With These DIYs"\n3. "I Tried 5 Viral DIY Projects"\n4. "DIY That Looks Store-Bought"\n5. "Easy Crafts for Beginners"' },
      { topic: 'Book recommendations', platform: 'YouTube', style: 'Thoughtful', keywords: 'books, reading, recommendations', aiOutput: '1. "Books That Changed My Perspective"\n2. "5 Books Everyone Should Read"\n3. "My Honest Book Reviews 2024"\n4. "Reading Vlog: 10 Books in 30 Days"\n5. "Books I\'ll Never Stop Recommending"' },
    ];

    await Title.bulkCreate(titlesData.map(item => ({ ...item, userId })));
    console.log('✅ Titles seeded');

    // Seed Descriptions (15+ items)
    const descriptionsData = [
      { videoTitle: 'Morning Routine 2024', topic: 'Productivity morning routine', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Start your day right with my complete morning routine! In this video, I share the habits that transformed my productivity.\n\nTIMESTAMPS:\n0:00 - Wake up routine\n2:30 - Morning meditation\n5:00 - Journaling practice\n8:00 - Workout session\n12:00 - Breakfast prep\n\nPRODUCTS MENTIONED:\n- Journal: [link]\n- Meditation app: [link]\n\n#morningroutine #productivity #lifestyle' },
      { videoTitle: 'iPhone 15 Review', topic: 'Tech review and analysis', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Is the iPhone 15 Pro Max worth upgrading to? After 30 days of use, here\'s my honest review.\n\nTIMESTAMPS:\n0:00 - Introduction\n1:30 - Unboxing\n4:00 - Design changes\n8:00 - Camera test\n15:00 - Performance\n20:00 - Final verdict\n\nSPECS & LINKS:\n- Apple Store: [link]\n\n#iPhone15 #TechReview #Apple' },
      { videoTitle: 'Tokyo Travel Vlog', topic: 'Japan travel guide', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Join me on an adventure through Tokyo! From hidden temples to amazing street food.\n\nPLACES VISITED:\n- Shibuya Crossing\n- Senso-ji Temple\n- Tsukiji Market\n- Harajuku District\n\nTRAVEL TIPS:\n- Best time to visit\n- Budget breakdown\n- Must-try foods\n\n#Tokyo #Japan #TravelVlog' },
      { videoTitle: 'Pasta Recipe', topic: 'Italian cooking tutorial', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Learn to make restaurant-quality pasta at home with this easy recipe!\n\nINGREDIENTS:\n- 400g flour\n- 4 eggs\n- Salt\n- Olive oil\n\nTIMESTAMPS:\n0:00 - Ingredients\n2:00 - Making dough\n8:00 - Rolling technique\n12:00 - Sauce prep\n\n#Cooking #Pasta #ItalianFood' },
      { videoTitle: 'Home Workout', topic: 'No equipment fitness', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'No gym? No problem! This 20-minute workout requires zero equipment.\n\nWORKOUT STRUCTURE:\n- Warm up: 3 min\n- Main workout: 15 min\n- Cool down: 2 min\n\nEXERCISES:\n1. Jumping jacks\n2. Push-ups\n3. Squats\n4. Planks\n5. Burpees\n\n#Fitness #HomeWorkout #NoEquipment' },
      { videoTitle: 'Room Tour 2024', topic: 'Content creator setup', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Complete tour of my content creation studio and setup!\n\nGEAR LIST:\n- Camera: Sony A7IV\n- Microphone: Shure SM7B\n- Lights: Elgato Key Light\n- Desk: IKEA BEKANT\n\nTOTAL SETUP COST: $5,000\n\nLinks to everything below!\n\n#RoomTour #Setup #Creator' },
      { videoTitle: 'Budget Tips', topic: 'Personal finance advice', platform: 'TikTok', includeLinks: false, includeCta: true, aiOutput: 'Money-saving tips that actually work! Save $500+ monthly with these simple changes.\n\nTIPS COVERED:\n1. Track expenses\n2. Budget apps\n3. Meal planning\n4. Cancel subscriptions\n5. No-spend challenges\n\nFollow for more finance tips!\n\n#MoneyTips #Budgeting #Finance' },
      { videoTitle: 'Study Session', topic: 'Productivity for students', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Study with me in real-time! 2-hour focused study session.\n\nSESSION FORMAT:\n- 4x 25-minute focus blocks\n- 5-minute breaks\n- Background music: lo-fi\n\nSTUDY TIPS:\n- Pomodoro technique\n- Note-taking methods\n- Focus strategies\n\n#StudyWithMe #Student #Productivity' },
      { videoTitle: 'Skincare Routine', topic: 'Beauty and self-care', platform: 'TikTok', includeLinks: true, includeCta: true, aiOutput: 'My complete skincare routine for clear skin!\n\nMORNING:\n1. Cleanser\n2. Toner\n3. Serum\n4. Moisturizer\n5. SPF\n\nNIGHT:\n1. Double cleanse\n2. Treatment\n3. Night cream\n\nAll products linked!\n\n#Skincare #Beauty #Routine' },
      { videoTitle: 'Gaming Setup Tour', topic: 'Gaming equipment review', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'My ultimate gaming setup tour 2024!\n\nSPECS:\n- PC: RTX 4090, i9\n- Monitor: 4K 144Hz\n- Keyboard: Custom mechanical\n- Mouse: Logitech G Pro\n\nTOTAL COST: $8,000\n\nAll links below!\n\n#Gaming #Setup #PCGaming' },
      { videoTitle: 'Vlog: Week in My Life', topic: 'Lifestyle content', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'A realistic week in my life as a content creator!\n\nTHIS WEEK:\n- Monday: Planning content\n- Tuesday: Filming day\n- Wednesday: Editing\n- Thursday: Meetings\n- Friday: Self-care\n\nFollow along with my journey!\n\n#WeekInMyLife #Vlog #Creator' },
      { videoTitle: 'Coffee Shop Work', topic: 'Remote work lifestyle', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Working from different coffee shops in my city!\n\nSHOPS VISITED:\n1. Starbucks Reserve\n2. Local indie cafe\n3. Hotel lobby\n4. Library cafe\n\nTIPS:\n- Best seating spots\n- WiFi speeds\n- Noise levels\n\n#RemoteWork #CoffeeShop #WFH' },
      { videoTitle: 'Unboxing Haul', topic: 'Product reviews', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Unboxing my latest tech and lifestyle purchases!\n\nIN THIS HAUL:\n1. New camera lens\n2. Desk accessories\n3. Smart home devices\n4. Organization items\n\nFirst impressions and honest thoughts!\n\n#Unboxing #Haul #Tech' },
      { videoTitle: 'Workout Challenge', topic: 'Fitness transformation', platform: 'TikTok', includeLinks: false, includeCta: true, aiOutput: '30-day workout challenge results!\n\nSTARTING STATS:\nWeight: 180 lbs\nBody fat: 25%\n\nFINAL STATS:\nWeight: 170 lbs\nBody fat: 20%\n\nWorkout plan in bio!\n\n#WorkoutChallenge #Fitness #Transformation' },
      { videoTitle: 'Apartment Tour', topic: 'Home decor and living', platform: 'YouTube', includeLinks: true, includeCta: true, aiOutput: 'Full tour of my city apartment!\n\nROOMS:\n- Living room\n- Kitchen\n- Bedroom\n- Home office\n- Bathroom\n\nDECOR STYLE: Modern minimalist\nRENT: $2,500/month\n\nAll decor items linked!\n\n#ApartmentTour #HomeDecor #Interior' },
    ];

    await Description.bulkCreate(descriptionsData.map(item => ({ ...item, userId })));
    console.log('✅ Descriptions seeded');

    // Seed Hashtags (15+ items)
    const hashtagsData = [
      { topic: 'Morning routine content', platform: 'TikTok', niche: 'Lifestyle', count: 15, aiOutput: '#morningroutine #productivity #lifestyle #grwm #routine #healthy #wellness #selfcare #motivation #fyp #viral #trending #dailyroutine #morningmotivation #habits' },
      { topic: 'Tech reviews', platform: 'YouTube', niche: 'Technology', count: 15, aiOutput: '#tech #technology #review #gadgets #techreview #apple #iphone #android #smartphone #unboxing #techyoutuber #techtok #newtech #gadgetreview #techie' },
      { topic: 'Travel content', platform: 'Instagram', niche: 'Travel', count: 15, aiOutput: '#travel #wanderlust #travelphotography #travelgram #explore #adventure #vacation #travelblogger #instatravel #traveling #tourism #trip #traveler #traveltheworld #travelholic' },
      { topic: 'Fitness content', platform: 'TikTok', niche: 'Fitness', count: 15, aiOutput: '#fitness #workout #gym #fit #motivation #health #training #exercise #fitnessmotivation #bodybuilding #healthy #lifestyle #muscle #fitfam #gains' },
      { topic: 'Food content', platform: 'Instagram', niche: 'Food', count: 15, aiOutput: '#food #foodie #foodporn #instafood #yummy #delicious #foodphotography #foodstagram #cooking #recipe #homemade #foodblogger #dinner #lunch #tasty' },
      { topic: 'Beauty tutorials', platform: 'TikTok', niche: 'Beauty', count: 15, aiOutput: '#beauty #makeup #skincare #beautytips #makeupartist #cosmetics #mua #beautyblogger #skincareroutine #makeuptutorial #glam #beautyhacks #makeuplover #beautyguru #skincaretips' },
      { topic: 'Gaming streams', platform: 'YouTube', niche: 'Gaming', count: 15, aiOutput: '#gaming #gamer #games #videogames #game #playstation #xbox #pc #twitch #streamer #gamingcommunity #esports #gameplay #gamers #pcgaming' },
      { topic: 'Fashion content', platform: 'Instagram', niche: 'Fashion', count: 15, aiOutput: '#fashion #style #ootd #fashionblogger #outfit #fashionista #streetstyle #instafashion #fashionstyle #lookoftheday #whatiwore #styleinspo #fashionable #trendy #fashionweek' },
      { topic: 'Study content', platform: 'YouTube', niche: 'Education', count: 15, aiOutput: '#study #studywithme #studygram #studymotivation #student #studytips #studying #education #school #university #college #learning #studentlife #studyblr #notes' },
      { topic: 'DIY projects', platform: 'Pinterest', niche: 'Crafts', count: 15, aiOutput: '#diy #crafts #handmade #homedecor #creative #craft #doityourself #homemade #art #design #decor #diycrafts #diyideas #diyproject #maker' },
      { topic: 'Pet content', platform: 'TikTok', niche: 'Pets', count: 15, aiOutput: '#pet #dog #cat #pets #dogsofinstagram #catsofinstagram #puppy #kitten #petlover #doglife #catlife #petsofinstagram #doglover #catlover #cute' },
      { topic: 'Music content', platform: 'YouTube', niche: 'Music', count: 15, aiOutput: '#music #musician #singer #guitar #piano #song #cover #singing #musicproduction #songwriter #band #rock #pop #hiphop #musicvideo' },
      { topic: 'Art content', platform: 'Instagram', niche: 'Art', count: 15, aiOutput: '#art #artist #artwork #drawing #illustration #painting #digitalart #artistsoninstagram #sketch #creative #design #arte #instaart #artoftheday #artistic' },
      { topic: 'Finance tips', platform: 'TikTok', niche: 'Finance', count: 15, aiOutput: '#finance #money #investing #wealth #financialfreedom #stocks #crypto #personalfinance #budget #savings #moneytips #financetips #invest #wealthbuilding #financialliteracy' },
      { topic: 'Motivation content', platform: 'Instagram', niche: 'Self-improvement', count: 15, aiOutput: '#motivation #inspiration #success #mindset #goals #entrepreneur #hustle #motivational #grind #ambition #positivity #believe #dreams #nevergiveup #successmindset' },
    ];

    await Hashtag.bulkCreate(hashtagsData.map(item => ({ ...item, userId })));
    console.log('✅ Hashtags seeded');

    // Seed Thumbnails (15+ items)
    const thumbnailsData = [
      { videoTitle: 'Morning Routine 2024', topic: 'Productivity morning habits', style: 'Clean and minimal', colorScheme: 'Blue and white', aiOutput: '**Thumbnail Concept**\n\n1. Split screen: "5 AM" on one side, energetic pose on other\n2. Large text: "CHANGED MY LIFE"\n3. Clock graphic showing 5:00 AM\n4. Bright, warm lighting to convey energy\n5. Coffee cup prop for relatability' },
      { videoTitle: 'iPhone 15 Review', topic: 'Tech product review', style: 'Professional tech', colorScheme: 'Black and silver', aiOutput: '**Thumbnail Concept**\n\n1. iPhone 15 at center with reflection effect\n2. Your face with surprised/impressed expression\n3. Text: "WORTH IT?" in bold\n4. Rating stars graphic (4.5/5)\n5. Clean dark background with subtle gradients' },
      { videoTitle: 'Tokyo Travel Vlog', topic: 'Japan adventure', style: 'Vibrant travel', colorScheme: 'Red and pink (cherry blossom)', aiOutput: '**Thumbnail Concept**\n\n1. Famous Tokyo landmark in background\n2. You in foreground with excited expression\n3. Cherry blossom overlay\n4. Text: "TOKYO" in Japanese-inspired font\n5. Map pin graphic element' },
      { videoTitle: 'Pasta Recipe', topic: 'Italian cooking', style: 'Appetizing food', colorScheme: 'Warm red and yellow', aiOutput: '**Thumbnail Concept**\n\n1. Close-up of steaming pasta dish\n2. Fork twirling pasta in action shot\n3. Italian flag colors subtly incorporated\n4. Text: "RESTAURANT QUALITY"\n5. Parmesan being grated (action shot)' },
      { videoTitle: 'Fitness Transformation', topic: '30-day challenge', style: 'Before/After', colorScheme: 'Green and orange', aiOutput: '**Thumbnail Concept**\n\n1. Before/after split image\n2. Arrow showing transformation direction\n3. "30 DAYS" text prominently displayed\n4. Measurements or stats overlay\n5. Motivational pose in after image' },
      { videoTitle: 'Budget Tips', topic: 'Money saving', style: 'Eye-catching finance', colorScheme: 'Green (money)', aiOutput: '**Thumbnail Concept**\n\n1. Stack of cash or coins visual\n2. Your shocked face looking at money\n3. Text: "$500/MONTH"\n4. Piggy bank graphic\n5. Dollar signs floating in background' },
      { videoTitle: 'Room Tour', topic: 'Setup showcase', style: 'Aesthetic tech', colorScheme: 'RGB/Neon', aiOutput: '**Thumbnail Concept**\n\n1. Wide shot of complete setup with RGB lighting\n2. Text: "DREAM SETUP"\n3. Price tag graphic "$5000"\n4. Before/after corner comparison\n5. Equipment icons highlighting key items' },
      { videoTitle: 'Storytime', topic: 'Personal journey', style: 'Emotional/dramatic', colorScheme: 'Warm tones', aiOutput: '**Thumbnail Concept**\n\n1. Emotional facial expression (thoughtful)\n2. Text: "THE TRUTH..."\n3. Old photo in corner (throwback element)\n4. Soft, emotional lighting\n5. Subtle tear or emotion indicator' },
      { videoTitle: 'Gaming Video', topic: 'Epic gameplay', style: 'Dynamic gaming', colorScheme: 'Game-specific colors', aiOutput: '**Thumbnail Concept**\n\n1. Epic in-game screenshot\n2. Your reaction face overlaid\n3. "INSANE!" or "NO WAY" text\n4. Game logo included\n5. Victory/achievement graphic' },
      { videoTitle: 'Makeup Tutorial', topic: 'Beauty transformation', style: 'Glamorous', colorScheme: 'Pink and gold', aiOutput: '**Thumbnail Concept**\n\n1. Half face bare, half with makeup\n2. Dramatic eye close-up\n3. Text: "5 MINUTE GLAM"\n4. Product placement (subtle)\n5. Sparkle/glitter overlay effects' },
      { videoTitle: 'Workout Routine', topic: 'Exercise tutorial', style: 'Energetic fitness', colorScheme: 'Bold red/black', aiOutput: '**Thumbnail Concept**\n\n1. Action shot mid-exercise\n2. Sweat/effort visible\n3. Text: "NO GYM NEEDED"\n4. Timer graphic "20 MIN"\n5. Energy lines/motion blur effect' },
      { videoTitle: 'Unboxing', topic: 'Product reveal', style: 'Mystery/excitement', colorScheme: 'Brand colors', aiOutput: '**Thumbnail Concept**\n\n1. Hands opening box from above\n2. Light/glow coming from inside box\n3. Question marks around box\n4. Text: "FINALLY!"\n5. Product partially visible' },
      { videoTitle: 'Q&A Video', topic: 'Fan questions', style: 'Personal/friendly', colorScheme: 'Bright and inviting', aiOutput: '**Thumbnail Concept**\n\n1. You with thinking/curious expression\n2. Question mark graphics floating\n3. Text: "I ANSWERED EVERYTHING"\n4. Comment/social media icons\n5. Friendly, approachable lighting' },
      { videoTitle: 'Day in My Life', topic: 'Daily vlog', style: 'Lifestyle aesthetic', colorScheme: 'Soft pastels', aiOutput: '**Thumbnail Concept**\n\n1. Split into sections showing different activities\n2. Golden hour lighting\n3. Text: "24 HOURS"\n4. Clock/time element\n5. Cozy, relatable vibe' },
      { videoTitle: 'Reaction Video', topic: 'Viral content reactions', style: 'Expressive', colorScheme: 'High contrast', aiOutput: '**Thumbnail Concept**\n\n1. Your most expressive reaction face\n2. Screenshot of video being reacted to\n3. Text: "I CAN\'T BELIEVE THIS"\n4. Arrow pointing to your reaction\n5. Bright, attention-grabbing background' },
    ];

    await Thumbnail.bulkCreate(thumbnailsData.map(item => ({ ...item, userId })));
    console.log('✅ Thumbnails seeded');

    // Seed Hooks (15+ items)
    const hooksData = [
      { topic: 'Morning routine productivity', platform: 'YouTube', hookType: 'Question', targetEmotion: 'Curiosity', aiOutput: '1. "What if I told you that one habit could change your entire life?"\n2. "Have you ever wondered why successful people wake up at 5 AM?"\n3. "What\'s the first thing you do when you wake up? Because this changed everything for me..."' },
      { topic: 'Tech review', platform: 'YouTube', hookType: 'Bold statement', targetEmotion: 'Intrigue', aiOutput: '1. "This is either the best phone ever made, or Apple made a huge mistake."\n2. "After 30 days with this phone, I need to tell you something important."\n3. "Forget everything you\'ve heard about this phone. Here\'s the truth."' },
      { topic: 'Travel content', platform: 'TikTok', hookType: 'Storytelling', targetEmotion: 'Adventure', aiOutput: '1. "I got lost in Tokyo at 2 AM... and it was the best thing that ever happened to me."\n2. "Nobody told me this about Japan before I went..."\n3. "This random stranger in Tokyo changed my entire trip."' },
      { topic: 'Fitness transformation', platform: 'TikTok', hookType: 'Shock value', targetEmotion: 'Motivation', aiOutput: '1. "I did this ONE exercise every day for 30 days. Look what happened."\n2. "They said I couldn\'t transform in 30 days. I proved them wrong."\n3. "The exercise that doctors don\'t want you to know about..."' },
      { topic: 'Money saving tips', platform: 'YouTube', hookType: 'Promise', targetEmotion: 'Hope', aiOutput: '1. "By the end of this video, you\'ll know exactly how to save $500 every month."\n2. "I\'m about to show you the exact system that got me out of debt."\n3. "This video contains information that could change your financial life forever."' },
      { topic: 'Cooking tutorial', platform: 'YouTube', hookType: 'Challenge', targetEmotion: 'Confidence', aiOutput: '1. "If you can follow these 5 steps, you can cook better than most restaurants."\n2. "Chefs charge $50 for this. You\'re about to learn it for free."\n3. "I guarantee you\'ve been making pasta wrong your entire life."' },
      { topic: 'Beauty tutorial', platform: 'TikTok', hookType: 'Relatable', targetEmotion: 'Connection', aiOutput: '1. "If you\'ve ever felt like makeup tutorials are impossible to follow, this is for you."\n2. "I used to spend 2 hours on my makeup. Now it takes 10 minutes."\n3. "POV: You finally found a makeup routine that actually works."' },
      { topic: 'Study tips', platform: 'YouTube', hookType: 'Authority', targetEmotion: 'Trust', aiOutput: '1. "As someone who graduated top of their class, these are the study methods that actually work."\n2. "After studying hundreds of research papers, I found the perfect study technique."\n3. "Scientists discovered this study method is 50% more effective."' },
      { topic: 'Gaming content', platform: 'YouTube', hookType: 'Excitement', targetEmotion: 'Anticipation', aiOutput: '1. "What you\'re about to see is probably the craziest play I\'ve ever made."\n2. "I\'ve been gaming for 10 years and I\'ve never seen anything like this."\n3. "The clutch that broke the internet..."' },
      { topic: 'Lifestyle vlog', platform: 'YouTube', hookType: 'Vulnerability', targetEmotion: 'Empathy', aiOutput: '1. "I need to be honest with you about something I\'ve been hiding..."\n2. "This is the video I never wanted to make, but I need to."\n3. "I\'ve been struggling with something, and I think you might be too."' },
      { topic: 'DIY projects', platform: 'TikTok', hookType: 'Demonstration', targetEmotion: 'Amazement', aiOutput: '1. "Watch me turn $10 worth of materials into a $200 piece of furniture."\n2. "Everyone told me this was impossible. I did it anyway."\n3. "This DIY hack is about to change your entire home."' },
      { topic: 'Fashion content', platform: 'TikTok', hookType: 'Transformation', targetEmotion: 'Inspiration', aiOutput: '1. "Watch how I turned this $20 outfit into a $500 look."\n2. "From basic to stunning in 3 easy steps..."\n3. "The outfit hack that fashion brands don\'t want you to know."' },
      { topic: 'Motivation', platform: 'YouTube', hookType: 'Story', targetEmotion: 'Inspiration', aiOutput: '1. "Two years ago, I was broke, alone, and ready to give up. Today..."\n2. "The moment I hit rock bottom was the moment everything changed."\n3. "If I had given up then, I never would have experienced this."' },
      { topic: 'Product review', platform: 'TikTok', hookType: 'Controversy', targetEmotion: 'Curiosity', aiOutput: '1. "Everyone is buying this product. Here\'s why you shouldn\'t."\n2. "I\'m about to say something that might make this brand hate me."\n3. "The truth about this viral product that nobody is talking about."' },
      { topic: 'Educational content', platform: 'YouTube', hookType: 'Mind-blowing fact', targetEmotion: 'Awe', aiOutput: '1. "Everything you learned about this in school was wrong."\n2. "Scientists just discovered something that changes everything we knew."\n3. "This fact will completely change how you see the world."' },
    ];

    await Hook.bulkCreate(hooksData.map(item => ({ ...item, userId })));
    console.log('✅ Hooks seeded');

    // Seed Calendars (15+ items)
    const calendarsData = [
      { niche: 'Tech reviews', platform: 'YouTube', frequency: '3 times per week', duration: '1 month', goals: 'Grow subscriber base, establish authority', aiOutput: '**Weekly Content Calendar**\n\nMONDAY: Product review/unboxing\nWEDNESDAY: Tutorial/How-to\nFRIDAY: News/Updates recap\n\nWeek 1: Smartphone focus\nWeek 2: Laptop focus\nWeek 3: Accessories\nWeek 4: Monthly best-of compilation' },
      { niche: 'Fitness', platform: 'TikTok', frequency: 'Daily', duration: '1 month', goals: 'Build community, increase engagement', aiOutput: '**Daily Content Plan**\n\nMONDAY: Workout routine\nTUESDAY: Nutrition tips\nWEDNESDAY: Transformation stories\nTHURSDAY: Exercise tutorials\nFRIDAY: Q&A\nSATURDAY: Challenge content\nSUNDAY: Motivational content' },
      { niche: 'Cooking', platform: 'YouTube', frequency: '2 times per week', duration: '1 month', goals: 'Recipe collection, cookbook promo', aiOutput: '**Bi-weekly Schedule**\n\nTUESDAY: Quick weeknight recipes\nSATURDAY: Special occasion cooking\n\nThemes:\nWeek 1: Italian cuisine\nWeek 2: Asian fusion\nWeek 3: Healthy eating\nWeek 4: Comfort food' },
      { niche: 'Beauty', platform: 'Instagram', frequency: '5 times per week', duration: '2 weeks', goals: 'Brand partnerships, product launches', aiOutput: '**Content Mix**\n\nMON: Tutorial reels\nTUE: Product review posts\nWED: GRWM stories\nTHU: Skin care routine\nFRI: Trending looks\n\nStory Schedule:\nDaily: Behind the scenes\nWeekly: Q&A sessions' },
      { niche: 'Gaming', platform: 'YouTube', frequency: '4 times per week', duration: '1 month', goals: 'Stream growth, community building', aiOutput: '**Gaming Calendar**\n\nMON: Let\'s Play series\nWED: Game reviews\nFRI: Stream highlights\nSUN: Community gaming\n\nMonthly Specials:\n- Week 2: New release coverage\n- Week 4: Retro gaming' },
      { niche: 'Travel', platform: 'YouTube', frequency: '1 time per week', duration: '3 months', goals: 'Destination guides, sponsorships', aiOutput: '**Travel Content Plan**\n\nMonth 1: Domestic destinations\nMonth 2: International adventures\nMonth 3: Budget travel series\n\nWeekly Format:\n- Destination vlogs\n- Travel tips\n- Cost breakdowns' },
      { niche: 'Finance', platform: 'TikTok', frequency: 'Daily', duration: '2 weeks', goals: 'Educational reach, course promo', aiOutput: '**Financial Education Calendar**\n\nDaily Topics:\nMON: Investing basics\nTUE: Budgeting tips\nWED: Debt payoff strategies\nTHU: Side hustle ideas\nFRI: Money myths debunked\nSAT: Success stories\nSUN: Weekly market recap' },
      { niche: 'Lifestyle', platform: 'YouTube', frequency: '2 times per week', duration: '1 month', goals: 'Authentic connection, brand building', aiOutput: '**Lifestyle Content Mix**\n\nWEDNESDAY: Vlogs/Day in life\nSUNDAY: Self-improvement content\n\nMonthly Themes:\nWeek 1: Productivity\nWeek 2: Self-care\nWeek 3: Home organization\nWeek 4: Reflection/goals' },
      { niche: 'Education', platform: 'YouTube', frequency: '3 times per week', duration: '1 month', goals: 'Course launch, authority building', aiOutput: '**Educational Content Plan**\n\nMON: Deep dive tutorials\nWED: Quick tips/tricks\nFRI: Q&A/Student showcase\n\nSeries Ideas:\n- Beginner fundamentals\n- Advanced techniques\n- Case studies' },
      { niche: 'Fashion', platform: 'Instagram', frequency: '4 times per week', duration: '1 month', goals: 'Style influence, affiliate sales', aiOutput: '**Fashion Calendar**\n\nMON: OOTD posts\nWED: Trend analysis reels\nFRI: Styling tips\nSUN: Haul/Try-on\n\nStories:\n- Daily outfit inspo\n- Shopping adventures\n- Style polls' },
      { niche: 'Music', platform: 'YouTube', frequency: '2 times per week', duration: '1 month', goals: 'Cover visibility, original releases', aiOutput: '**Music Content Schedule**\n\nTUESDAY: Cover songs\nSATURDAY: Original music/Behind scenes\n\nMonthly Goals:\n- 4 cover videos\n- 2 original tracks\n- 4 studio vlogs\n- 2 collaboration features' },
      { niche: 'Pet content', platform: 'TikTok', frequency: 'Daily', duration: '2 weeks', goals: 'Viral potential, brand deals', aiOutput: '**Pet Content Calendar**\n\nContent Types:\n- Morning routines\n- Training sessions\n- Funny moments\n- Product reviews\n- Day in the life\n\nTrending Content:\n- React to trends\n- Challenge participation' },
      { niche: 'DIY/Crafts', platform: 'Pinterest', frequency: '5 times per week', duration: '1 month', goals: 'Pin engagement, blog traffic', aiOutput: '**DIY Content Plan**\n\nDaily Pin Schedule:\n- 2 project pins\n- 1 tip pin\n- 2 repins\n\nProject Categories:\nWeek 1: Home decor\nWeek 2: Organization\nWeek 3: Seasonal crafts\nWeek 4: Budget DIYs' },
      { niche: 'Photography', platform: 'Instagram', frequency: '3 times per week', duration: '1 month', goals: 'Portfolio building, client acquisition', aiOutput: '**Photography Calendar**\n\nMON: Portfolio shots\nWED: Behind the scenes\nFRI: Editing tutorials\n\nContent Mix:\n- Landscape\n- Portrait\n- Street photography\n- Editing tips' },
      { niche: 'Motivation', platform: 'YouTube', frequency: '1 time per week', duration: '1 month', goals: 'Speaking engagements, course sales', aiOutput: '**Motivational Content Plan**\n\nSUNDAY: Weekly inspiration video\n\nTopics:\nWeek 1: Overcoming fear\nWeek 2: Building habits\nWeek 3: Success mindset\nWeek 4: Goal setting\n\nBonus: Monthly live Q&A' },
    ];

    await Calendar.bulkCreate(calendarsData.map(item => ({ ...item, userId })));
    console.log('✅ Calendars seeded');

    // Seed Trends (15+ items)
    const trendsData = [
      { niche: 'Technology', platform: 'YouTube', timeframe: 'This week', region: 'Global', aiOutput: '**Current Tech Trends**\n\n1. AI tools and ChatGPT alternatives\n2. Foldable phones and new releases\n3. Gaming hardware updates\n4. Smart home automation\n5. Wearable tech innovations\n\nEmerging: Spatial computing, AR glasses' },
      { niche: 'Fitness', platform: 'TikTok', timeframe: 'This month', region: 'US', aiOutput: '**Fitness Trends**\n\n1. 12-3-30 treadmill workout\n2. Hot girl walks\n3. Pilates renaissance\n4. Carnivore diet discussions\n5. Hybrid athlete training\n\nViral Challenges: 75 Hard, 30-day planks' },
      { niche: 'Beauty', platform: 'Instagram', timeframe: 'This week', region: 'Global', aiOutput: '**Beauty Trends**\n\n1. Clean girl aesthetic\n2. Glass skin routines\n3. Strawberry girl makeup\n4. Hair slugging\n5. Mob wife aesthetic\n\nProducts: Skin tints, lip oils, hair treatments' },
      { niche: 'Fashion', platform: 'TikTok', timeframe: 'This month', region: 'US', aiOutput: '**Fashion Trends**\n\n1. Quiet luxury\n2. Coquette style\n3. Normcore revival\n4. Platform shoes\n5. Oversized everything\n\nColors: Burgundy, olive green, camel' },
      { niche: 'Food', platform: 'YouTube', timeframe: 'This week', region: 'Global', aiOutput: '**Food Trends**\n\n1. Dubai chocolate bars\n2. Protein-focused recipes\n3. Air fryer everything\n4. Cottage cheese creations\n5. Korean corn dogs\n\nDiets: Mediterranean, carnivore debates' },
      { niche: 'Gaming', platform: 'YouTube', timeframe: 'This month', region: 'Global', aiOutput: '**Gaming Trends**\n\n1. New AAA releases\n2. Indie game discoveries\n3. Speedrunning communities\n4. Cozy gaming content\n5. VR gaming growth\n\nPlatforms: Steam Deck, PS5, retro gaming' },
      { niche: 'Finance', platform: 'TikTok', timeframe: 'This week', region: 'US', aiOutput: '**Finance Trends**\n\n1. FIRE movement content\n2. Dividend investing\n3. Side hustle culture\n4. No-spend challenges\n5. AI stock trading\n\nTopics: Real estate, crypto recovery, recession prep' },
      { niche: 'Self-improvement', platform: 'YouTube', timeframe: 'This month', region: 'Global', aiOutput: '**Self-improvement Trends**\n\n1. Dopamine detox\n2. 5 AM club content\n3. Atomic habits discussions\n4. Monk mode challenges\n5. Stoicism content\n\nFormats: Long-form essays, day in life' },
      { niche: 'Travel', platform: 'Instagram', timeframe: 'This month', region: 'Global', aiOutput: '**Travel Trends**\n\n1. Solo travel content\n2. Budget backpacking\n3. Digital nomad lifestyle\n4. Off-season travel\n5. Sustainable tourism\n\nDestinations: Japan, Portugal, Bali, Mexico' },
      { niche: 'Music', platform: 'TikTok', timeframe: 'This week', region: 'Global', aiOutput: '**Music Trends**\n\n1. Trending sounds\n2. Cover song challenges\n3. Music production content\n4. Remix culture\n5. AI music tools\n\nGenres: Electronic, indie pop, nostalgic hits' },
      { niche: 'Pet content', platform: 'TikTok', timeframe: 'This week', region: 'Global', aiOutput: '**Pet Content Trends**\n\n1. Pet reaction videos\n2. Training transformations\n3. Talking pet buttons\n4. Pet fashion\n5. Rescue stories\n\nPopular: Dogs, cats, exotic pets' },
      { niche: 'Education', platform: 'YouTube', timeframe: 'This month', region: 'Global', aiOutput: '**Educational Trends**\n\n1. AI tutorials\n2. Coding bootcamp content\n3. Language learning\n4. History deep dives\n5. Science explainers\n\nFormats: Short tutorials, documentary style' },
      { niche: 'Comedy', platform: 'TikTok', timeframe: 'This week', region: 'US', aiOutput: '**Comedy Trends**\n\n1. Relatable content\n2. Sketch comedy\n3. Observational humor\n4. Trend participation with twist\n5. Character-based content\n\nStyles: Deadpan, absurdist, self-deprecating' },
      { niche: 'Home decor', platform: 'Instagram', timeframe: 'This month', region: 'Global', aiOutput: '**Home Decor Trends**\n\n1. Japandi style\n2. Curved furniture\n3. Terracotta tones\n4. Maximalism return\n5. Vintage revival\n\nDIY: Thrift flips, room makeovers' },
      { niche: 'Wellness', platform: 'YouTube', timeframe: 'This month', region: 'Global', aiOutput: '**Wellness Trends**\n\n1. Cold plunge content\n2. Breathwork sessions\n3. Sleep optimization\n4. Gut health focus\n5. Digital minimalism\n\nSupplements: Magnesium, adaptogens, probiotics' },
    ];

    await Trend.bulkCreate(trendsData.map(item => ({ ...item, userId })));
    console.log('✅ Trends seeded');

    // Seed Comments (15+ items)
    const commentsData = [
      { originalComment: 'This video changed my life! Thank you so much!', context: 'Motivational content video', tone: 'Grateful and warm', platform: 'YouTube', aiOutput: 'Thank you so much for sharing this! Comments like yours are exactly why I create content. I\'m so happy this resonated with you. Keep pushing forward - you\'ve got this! Would love to hear about your journey in my next video\'s comments!' },
      { originalComment: 'Can you do a tutorial on editing?', context: 'Behind the scenes video', tone: 'Helpful and encouraging', platform: 'YouTube', aiOutput: 'Great suggestion! I\'ve actually been planning an editing tutorial series. I\'ll add this to my content calendar! In the meantime, I use DaVinci Resolve - it\'s free and amazing for beginners. Stay tuned!' },
      { originalComment: 'This is wrong, you don\'t know what you\'re talking about', context: 'Educational/review video', tone: 'Professional and respectful', platform: 'YouTube', aiOutput: 'I appreciate you sharing your perspective! I\'d love to learn more about your experience with this. Could you share what specifically you\'d approach differently? Always looking to improve and provide accurate information to the community.' },
      { originalComment: 'What camera do you use?', context: 'Any video', tone: 'Informative', platform: 'YouTube', aiOutput: 'Great question! I\'m currently using the Sony A7IV with a 24-70mm lens. For my TikToks, I just use my iPhone 15 Pro. I have a full gear list in my video description! Let me know if you have any other questions.' },
      { originalComment: 'First!', context: 'Any video', tone: 'Playful and engaging', platform: 'YouTube', aiOutput: 'And a great first commenter you are! Thanks for being here early and supporting the channel. What did you think of the video? Would love to hear your thoughts!' },
      { originalComment: 'I\'ve been following you since you had 100 subscribers!', context: 'Milestone video', tone: 'Appreciative', platform: 'YouTube', aiOutput: 'Wow, you\'re a real OG! I can\'t thank you enough for being on this journey with me from the beginning. You\'ve literally watched me grow, and that means everything. Here\'s to many more milestones together!' },
      { originalComment: 'This video was too long', context: 'Tutorial video', tone: 'Understanding but confident', platform: 'YouTube', aiOutput: 'Thanks for the feedback! I know longer videos aren\'t for everyone. I\'ve added timestamps in the description so you can jump to the sections most relevant to you. I also have shorter versions on my TikTok if that\'s more your style!' },
      { originalComment: 'Can we collab?', context: 'Any video', tone: 'Professional but friendly', platform: 'Instagram', aiOutput: 'Hey! Always open to collaborations with creators who share similar values. Send me a DM with your channel/content and some ideas you have in mind. Let\'s see if we can create something awesome together!' },
      { originalComment: 'When\'s your next upload?', context: 'Any video', tone: 'Excited', platform: 'YouTube', aiOutput: 'So glad you\'re looking forward to more content! I upload every Tuesday and Friday. Hit the notification bell so you don\'t miss the next one - I\'ve got something really special coming up!' },
      { originalComment: 'This is literally me every morning lol', context: 'Relatable content', tone: 'Fun and relatable', platform: 'TikTok', aiOutput: 'Haha, we\'re all the same! The morning struggle is REAL. At least we\'re in this together! Drop a coffee emoji if you can\'t function without caffeine like me.' },
      { originalComment: 'You should try [product/technique]', context: 'Tutorial/review', tone: 'Open and interested', platform: 'YouTube', aiOutput: 'Oh interesting suggestion! I\'ve heard about that but haven\'t tried it yet. I\'ll definitely look into it for a future video. Have you tried it personally? Would love to hear your experience!' },
      { originalComment: 'This was so helpful, saved for later!', context: 'Educational content', tone: 'Encouraging', platform: 'Instagram', aiOutput: 'Yes! Save it and come back whenever you need a refresher. I\'m so glad this was helpful! Feel free to DM me if you have any questions when you try implementing this.' },
      { originalComment: 'You copied [other creator]', context: 'Any video', tone: 'Calm and professional', platform: 'TikTok', aiOutput: 'I understand why you might think that! Actually, this is a pretty common topic/trend that many creators cover. I try to bring my own perspective and style to everything I create. I have respect for all creators in this space!' },
      { originalComment: 'The audio quality could be better', context: 'Any video', tone: 'Receptive to feedback', platform: 'YouTube', aiOutput: 'You\'re right, and I appreciate the honest feedback! I\'ve actually just upgraded my audio setup, so future videos should sound much better. Thanks for helping me improve!' },
      { originalComment: 'Best content on the platform!', context: 'Any video', tone: 'Humble and grateful', platform: 'YouTube', aiOutput: 'Wow, that means so much! I\'m just trying to create value for this amazing community. Thank you for being here and for the kind words. You all motivate me to keep improving!' },
    ];

    await Comment.bulkCreate(commentsData.map(item => ({ ...item, userId })));
    console.log('✅ Comments seeded');

    // Seed Ideas (15+ items)
    const ideasData = [
      { niche: 'Technology', platform: 'YouTube', contentType: 'Review', targetAudience: 'Tech enthusiasts 18-35', aiOutput: '**10 Video Ideas:**\n\n1. "I Used Only [New Product] for 30 Days"\n2. "Tech I Regret Buying vs Best Purchases"\n3. "Building My Dream Setup on a Budget"\n4. "$100 vs $1000 - Is Expensive Tech Worth It?"\n5. "Unpopular Tech Opinions"\n6. "Tech That Changed My Life This Year"\n7. "Reacting to My First Tech Video"\n8. "What\'s In My Tech Bag 2024"\n9. "Tech Fails I\'ve Made So You Don\'t Have To"\n10. "Future Tech That Will Change Everything"' },
      { niche: 'Fitness', platform: 'TikTok', contentType: 'Tutorial', targetAudience: 'Fitness beginners 18-30', aiOutput: '**10 Video Ideas:**\n\n1. "Exercises You\'re Doing Wrong"\n2. "5-Minute Ab Routine That Actually Works"\n3. "Foods That Are Secretly Killing Your Gains"\n4. "My Transformation Timeline"\n5. "Gym Mistakes I Made as a Beginner"\n6. "What I Eat in a Day (Realistic)"\n7. "Morning Routine for Maximum Energy"\n8. "Recovery Day Essentials"\n9. "Budget Supplements That Work"\n10. "Workout Split That Changed My Body"' },
      { niche: 'Cooking', platform: 'YouTube', contentType: 'Recipe', targetAudience: 'Home cooks 25-45', aiOutput: '**10 Video Ideas:**\n\n1. "5 Meals I Make Every Week"\n2. "Recreating My Grandma\'s Secret Recipe"\n3. "Restaurant vs Homemade Challenge"\n4. "1 Ingredient 5 Ways"\n5. "Meal Prep Sunday: Full Week"\n6. "Kitchen Tools That Changed My Cooking"\n7. "Cooking for a Professional Chef"\n8. "Budget Meals Under $5"\n9. "Taste Testing Viral Recipes"\n10. "My Biggest Kitchen Fails"' },
      { niche: 'Beauty', platform: 'Instagram', contentType: 'Tutorial', targetAudience: 'Beauty enthusiasts 16-35', aiOutput: '**10 Content Ideas:**\n\n1. "Drugstore Dupes for High-End Products"\n2. "Get Ready With Me: Different Occasions"\n3. "Skincare Routine AM/PM"\n4. "Products I\'ve Used Up and Repurchased"\n5. "Makeup Bag Declutter"\n6. "Recreating Celebrity Looks"\n7. "Brutally Honest Product Reviews"\n8. "Makeup Through the Decades"\n9. "What I\'d Buy at Sephora With $100"\n10. "Common Makeup Mistakes & Fixes"' },
      { niche: 'Gaming', platform: 'YouTube', contentType: 'Entertainment', targetAudience: 'Gamers 16-30', aiOutput: '**10 Video Ideas:**\n\n1. "Ranking Every Game I Played This Year"\n2. "I Tried to Speedrun [Game]"\n3. "Playing Games Based on Your Suggestions"\n4. "Evolution of [Game Series]"\n5. "My Gaming Setup Tour + Upgrades"\n6. "Playing My Childhood Games Again"\n7. "Challenge Runs: Beating Games the Hard Way"\n8. "Unpopular Gaming Opinions"\n9. "Best & Worst Games of the Year"\n10. "Playing With Subscribers"' },
      { niche: 'Finance', platform: 'TikTok', contentType: 'Educational', targetAudience: 'Young professionals 22-35', aiOutput: '**10 Video Ideas:**\n\n1. "Money Rules I Follow"\n2. "How I Budget My Salary"\n3. "Investment Mistakes to Avoid"\n4. "Side Hustles That Actually Pay"\n5. "Unpopular Money Opinions"\n6. "Breaking Down My Monthly Expenses"\n7. "Financial Goals at Every Age"\n8. "Building Credit the Right Way"\n9. "Apps That Save Me Money"\n10. "Questions to Ask Before Big Purchases"' },
      { niche: 'Travel', platform: 'YouTube', contentType: 'Vlog', targetAudience: 'Travel enthusiasts 25-40', aiOutput: '**10 Video Ideas:**\n\n1. "Traveling [Destination] on $50/Day"\n2. "Things I Wish I Knew Before Visiting"\n3. "Hidden Gems Tourists Don\'t Know"\n4. "Packing Guide for [Type of Trip]"\n5. "Travel Fails & What I Learned"\n6. "Trying Local Food in [Destination]"\n7. "Day in My Life: Digital Nomad"\n8. "Hostel vs Hotel Experience"\n9. "Solo Travel Tips for Beginners"\n10. "My Travel Photography Setup"' },
      { niche: 'Lifestyle', platform: 'YouTube', contentType: 'Vlog', targetAudience: 'Young adults 18-30', aiOutput: '**10 Video Ideas:**\n\n1. "Realistic Week in My Life"\n2. "Apartment/Room Tour & Organization"\n3. "My Productive Morning Routine"\n4. "Life Update: Where I\'ve Been"\n5. "Things I Stopped Buying"\n6. "How I Stay Organized"\n7. "Self-Care Sunday Routine"\n8. "Adulting 101: What I\'ve Learned"\n9. "Day in My Life: Work Edition"\n10. "Monthly Reset Routine"' },
      { niche: 'Education', platform: 'YouTube', contentType: 'Tutorial', targetAudience: 'Students and learners', aiOutput: '**10 Video Ideas:**\n\n1. "Study With Me: Real Time"\n2. "Note-Taking Methods Compared"\n3. "How I Learn Anything Fast"\n4. "Apps That Changed How I Study"\n5. "Exam Preparation Strategy"\n6. "Study Routine That Got Me A\'s"\n7. "Learning [Skill] from Scratch"\n8. "Time Management for Students"\n9. "How to Stay Focused While Studying"\n10. "Student Life Tips I Wish I Knew"' },
      { niche: 'Fashion', platform: 'TikTok', contentType: 'Style', targetAudience: 'Fashion-forward 16-30', aiOutput: '**10 Video Ideas:**\n\n1. "Building a Capsule Wardrobe"\n2. "Styling 1 Item 5 Ways"\n3. "Thrift Haul Try-On"\n4. "My Most Worn Pieces"\n5. "Fashion Trends I Love/Hate"\n6. "Get Dressed With Me"\n7. "Closet Organization & Declutter"\n8. "Outfit Ideas for [Season/Event]"\n9. "Rating My Old Outfits"\n10. "Shopping My Own Closet"' },
      { niche: 'Music', platform: 'YouTube', contentType: 'Performance', targetAudience: 'Music lovers 16-35', aiOutput: '**10 Video Ideas:**\n\n1. "Learning [Song] in 24 Hours"\n2. "Reacting to My First Cover"\n3. "Writing a Song in 1 Day"\n4. "Music Production Setup Tour"\n5. "Covering Songs You Requested"\n6. "Musical Journey Storytime"\n7. "Trying Different Music Genres"\n8. "Mashup of Popular Songs"\n9. "Behind the Scenes: Recording"\n10. "Acoustic Versions of Pop Hits"' },
      { niche: 'Pet content', platform: 'TikTok', contentType: 'Entertainment', targetAudience: 'Pet owners 18-45', aiOutput: '**10 Video Ideas:**\n\n1. "Day in My Pet\'s Life"\n2. "Testing Viral Pet Products"\n3. "Training Progress Compilation"\n4. "Pet\'s Reaction to [Trend]"\n5. "Morning Routine With My Pet"\n6. "What My Pet Does When I\'m Gone"\n7. "Pet Food Taste Test"\n8. "DIY Pet Projects"\n9. "Pet Adoption Story"\n10. "Things Only Pet Owners Understand"' },
      { niche: 'DIY/Crafts', platform: 'YouTube', contentType: 'Tutorial', targetAudience: 'Creative hobbyists 25-45', aiOutput: '**10 Video Ideas:**\n\n1. "Room Makeover on a Budget"\n2. "Thrift Flip: Furniture Edition"\n3. "5-Minute Crafts (That Actually Work)"\n4. "DIY Home Decor Ideas"\n5. "Organizing Craft Supplies"\n6. "Testing Viral DIY Hacks"\n7. "Seasonal Decorations DIY"\n8. "Beginner-Friendly Projects"\n9. "DIY Gift Ideas"\n10. "Failed DIYs & What Went Wrong"' },
      { niche: 'Health', platform: 'YouTube', contentType: 'Educational', targetAudience: 'Health-conscious 25-45', aiOutput: '**10 Video Ideas:**\n\n1. "What I Eat in a Week"\n2. "Morning Routine for Energy"\n3. "Supplements I Take & Why"\n4. "Sleep Optimization Tips"\n5. "Mental Health Check-In"\n6. "Healthy Habits That Changed My Life"\n7. "Grocery Haul & Meal Planning"\n8. "Hydration Challenge Results"\n9. "Realistic Self-Care Day"\n10. "Health Myths Debunked"' },
      { niche: 'Motivation', platform: 'YouTube', contentType: 'Inspirational', targetAudience: 'Ambitious individuals 18-40', aiOutput: '**10 Video Ideas:**\n\n1. "From Rock Bottom to Here"\n2. "Habits of Successful People"\n3. "How I Stay Motivated"\n4. "Goal Setting That Works"\n5. "Overcoming Fear of Failure"\n6. "Morning Routine for Success"\n7. "Life Lessons I Learned the Hard Way"\n8. "Day in My Life: Productivity Edition"\n9. "What No One Tells You About Success"\n10. "Building Discipline: My Journey"' },
    ];

    await Idea.bulkCreate(ideasData.map(item => ({ ...item, userId })));
    console.log('✅ Ideas seeded');

    // Seed SEO (15+ items)
    const seoData = [
      { videoTitle: 'Morning Routine 2024', description: 'My productive morning routine for success', platform: 'YouTube', targetKeywords: 'morning routine, productivity, wake up early', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "5 AM Morning Routine That Changed My Life | 2024 Productivity"\n\n**Keywords to Include:**\nPrimary: morning routine 2024\nSecondary: productive morning, wake up early, success habits\n\n**Tags:** morning routine, productivity tips, 5am club, morning motivation, daily routine' },
      { videoTitle: 'iPhone Review', description: 'Complete review of the new iPhone', platform: 'YouTube', targetKeywords: 'iPhone 15 review, Apple, tech review', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "iPhone 15 Pro Max Review - 30 Days Later | Honest Opinion"\n\n**Keywords:**\nPrimary: iPhone 15 review\nSecondary: iPhone 15 Pro Max, Apple review, should I upgrade\n\n**Tags:** iPhone 15, tech review, Apple, smartphone, iPhone comparison' },
      { videoTitle: 'Pasta Recipe', description: 'Easy homemade pasta tutorial', platform: 'YouTube', targetKeywords: 'pasta recipe, homemade pasta, Italian cooking', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "Restaurant-Quality Pasta at Home | Easy Recipe"\n\n**Keywords:**\nPrimary: homemade pasta recipe\nSecondary: easy pasta, Italian cooking, pasta from scratch\n\n**Tags:** pasta recipe, cooking tutorial, Italian food, homemade, easy recipes' },
      { videoTitle: 'Workout Routine', description: 'Full body workout no equipment', platform: 'YouTube', targetKeywords: 'home workout, no equipment, fitness', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "20-Minute Full Body Workout | No Equipment Needed"\n\n**Keywords:**\nPrimary: home workout no equipment\nSecondary: full body workout, at home exercise, bodyweight workout\n\n**Tags:** workout, fitness, home exercise, no gym, full body' },
      { videoTitle: 'Budget Tips', description: 'How to save money monthly', platform: 'YouTube', targetKeywords: 'save money, budgeting, personal finance', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "How I Save $500 Every Month | Realistic Budget Tips"\n\n**Keywords:**\nPrimary: how to save money\nSecondary: budgeting tips, personal finance, money saving\n\n**Tags:** budgeting, save money, personal finance, money tips, frugal living' },
      { videoTitle: 'Room Tour', description: 'My content creation setup', platform: 'YouTube', targetKeywords: 'room tour, setup tour, creator setup', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "Dream Content Creator Setup Tour 2024 | Room Tour"\n\n**Keywords:**\nPrimary: room tour 2024\nSecondary: setup tour, creator setup, desk setup\n\n**Tags:** room tour, setup, desk setup, content creator, home office' },
      { videoTitle: 'Makeup Tutorial', description: 'Easy everyday makeup look', platform: 'YouTube', targetKeywords: 'makeup tutorial, everyday makeup, easy makeup', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "5-Minute Everyday Makeup Tutorial | Natural Look"\n\n**Keywords:**\nPrimary: everyday makeup tutorial\nSecondary: natural makeup, easy makeup look, quick makeup\n\n**Tags:** makeup tutorial, everyday makeup, natural look, beauty, cosmetics' },
      { videoTitle: 'Study Tips', description: 'How to study effectively for exams', platform: 'YouTube', targetKeywords: 'study tips, exam preparation, student tips', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "Study Tips That Actually Work | How to Get A\'s"\n\n**Keywords:**\nPrimary: study tips\nSecondary: how to study, exam preparation, effective studying\n\n**Tags:** study tips, student, exam prep, productivity, learning' },
      { videoTitle: 'Travel Vlog', description: 'First time visiting Japan', platform: 'YouTube', targetKeywords: 'Japan travel, Tokyo vlog, travel guide', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "Japan Travel Vlog | First Time in Tokyo 2024"\n\n**Keywords:**\nPrimary: Japan travel vlog\nSecondary: Tokyo guide, Japan trip, visiting Japan\n\n**Tags:** Japan, Tokyo, travel vlog, Japan travel, Asia trip' },
      { videoTitle: 'Gaming Video', description: 'Best plays compilation', platform: 'YouTube', targetKeywords: 'gaming, gameplay, best moments', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "[Game Name] Best Moments | Insane Plays Compilation"\n\n**Keywords:**\nPrimary: [game] gameplay\nSecondary: best plays, gaming moments, highlights\n\n**Tags:** gaming, gameplay, best moments, highlights, [game name]' },
      { videoTitle: 'Skincare Routine', description: 'My skincare routine for clear skin', platform: 'TikTok', targetKeywords: 'skincare routine, clear skin, skincare tips', aiOutput: '**SEO Optimization Report**\n\n**Title/Caption:**\n- "Skincare routine that CLEARED my skin"\n\n**Keywords:**\nskincare, clear skin, glass skin, skincare routine, glow up\n\n**Hashtags:** #skincare #clearskin #skincareroutine #glowup #beautytok' },
      { videoTitle: 'Cooking Hack', description: 'Kitchen hacks that save time', platform: 'TikTok', targetKeywords: 'cooking hacks, kitchen tips, time saving', aiOutput: '**SEO Optimization Report**\n\n**Title/Caption:**\n- "Kitchen hack that changed my life"\n\n**Keywords:**\ncooking hack, kitchen tip, time saver, food hack, cooking tip\n\n**Hashtags:** #cookinghack #kitchenhacks #foodtok #cooking #lifehack' },
      { videoTitle: 'Fashion Haul', description: 'Try on clothing haul', platform: 'YouTube', targetKeywords: 'clothing haul, try on haul, fashion', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "Massive Try-On Clothing Haul | [Store Name] 2024"\n\n**Keywords:**\nPrimary: clothing haul\nSecondary: try on haul, fashion haul, new clothes\n\n**Tags:** haul, clothing, fashion, try on, shopping haul' },
      { videoTitle: 'Day in My Life', description: 'Realistic day as content creator', platform: 'YouTube', targetKeywords: 'day in my life, vlog, content creator life', aiOutput: '**SEO Optimization Report**\n\n**Title Suggestions:**\n- "Day in My Life as a Full-Time Content Creator | Realistic Vlog"\n\n**Keywords:**\nPrimary: day in my life\nSecondary: content creator, vlog, daily routine\n\n**Tags:** day in my life, vlog, content creator, daily routine, lifestyle' },
      { videoTitle: 'Product Review', description: 'Honest review of viral product', platform: 'TikTok', targetKeywords: 'review, product review, honest review', aiOutput: '**SEO Optimization Report**\n\n**Title/Caption:**\n- "Honest review of [Product] - worth the hype?"\n\n**Keywords:**\nreview, honest review, product review, worth it, viral product\n\n**Hashtags:** #review #productreview #honest #worthit #viral' },
    ];

    await Seo.bulkCreate(seoData.map(item => ({ ...item, userId })));
    console.log('✅ SEO data seeded');

    // Seed Analytics (15+ items)
    const analyticsData = [
      { platform: 'YouTube', metricType: 'Views', dataInput: 'Last video: 50K views, Avg views: 30K, Best video: 200K views', timeframe: 'Last 30 days', aiOutput: '**Analytics Insights**\n\n**Performance:** Your last video outperformed your average by 67%!\n\n**Patterns:**\n- Videos posted on Tuesday perform 40% better\n- 10-15 minute videos get best retention\n\n**Recommendations:**\n1. Analyze your 200K video - replicate elements\n2. Post more content similar to your recent hit\n3. Optimize upload time to 6 PM' },
      { platform: 'TikTok', metricType: 'Engagement', dataInput: 'Avg likes: 5K, Avg comments: 200, Avg shares: 500', timeframe: 'Last 7 days', aiOutput: '**Engagement Analysis**\n\n**Strong Points:**\n- Share rate is above average\n- Comment engagement is healthy\n\n**Areas to Improve:**\n- Increase CTA for comments\n- Use more trending sounds\n\n**Recommendations:**\n1. Ask questions in captions\n2. Respond to comments quickly\n3. Create duet-able content' },
      { platform: 'Instagram', metricType: 'Followers', dataInput: 'Gained 2K followers, Lost 500, Net: +1500', timeframe: 'Last 30 days', aiOutput: '**Follower Analysis**\n\n**Growth Rate:** +1500/month is solid growth!\n\n**Insights:**\n- Reels driving most new followers\n- Story engagement affects retention\n\n**Recommendations:**\n1. Post more Reels content\n2. Use Stories to engage existing followers\n3. Collaborate with similar-sized accounts' },
      { platform: 'YouTube', metricType: 'Watch Time', dataInput: 'Total: 50K hours, Avg per video: 3K hours, Retention: 45%', timeframe: 'Last 30 days', aiOutput: '**Watch Time Analysis**\n\n**Good:** 45% retention is above average\n\n**Observations:**\n- First 30 seconds crucial for retention\n- Drop-off at 6-minute mark\n\n**Recommendations:**\n1. Stronger hooks in first 30 seconds\n2. Add pattern interrupts at 6-minute mark\n3. Keep videos under 12 minutes initially' },
      { platform: 'TikTok', metricType: 'For You Page', dataInput: 'FYP views: 80%, Followers: 20%', timeframe: 'Last 7 days', aiOutput: '**FYP Performance**\n\n**Great news:** 80% of views from FYP indicates strong algorithm favor!\n\n**Strategy:**\n- Your content is discovery-friendly\n- Focus on converting viewers to followers\n\n**Recommendations:**\n1. Add follow CTAs\n2. Create series content\n3. Post at peak times (7-9 PM)' },
      { platform: 'YouTube', metricType: 'CTR', dataInput: 'Avg CTR: 6%, Best CTR: 12%, Lowest CTR: 2%', timeframe: 'Last 30 days', aiOutput: '**Click-Through Rate Analysis**\n\n**Performance:** 6% CTR is good (benchmark: 4-10%)\n\n**Patterns:**\n- 12% CTR video: Strong thumbnail + title combo\n- 2% CTR: Likely poor thumbnail\n\n**Recommendations:**\n1. A/B test thumbnails\n2. Use faces in thumbnails\n3. Add contrast and bright colors' },
      { platform: 'Instagram', metricType: 'Reach', dataInput: 'Reels reach: 50K, Posts: 10K, Stories: 5K', timeframe: 'Last 7 days', aiOutput: '**Reach Analysis**\n\n**Clear winner:** Reels get 5x the reach!\n\n**Strategy Shift:**\n- Prioritize Reels content\n- Use posts for community building\n- Stories for engagement\n\n**Recommendations:**\n1. Create more Reels (3-5/week)\n2. Repurpose TikToks to Reels\n3. Use trending audio' },
      { platform: 'YouTube', metricType: 'Subscribers', dataInput: 'Gained: 5000, Lost: 500, Net: +4500', timeframe: 'Last 30 days', aiOutput: '**Subscriber Analysis**\n\n**Excellent growth!** +4500/month\n\n**Sources:**\n- Video suggestions: 60%\n- Search: 25%\n- External: 15%\n\n**Recommendations:**\n1. Create searchable content (tutorials)\n2. Add end screens for subscriptions\n3. Cross-promote on other platforms' },
      { platform: 'TikTok', metricType: 'Completion Rate', dataInput: 'Avg completion: 65%, Best: 90%, Lowest: 30%', timeframe: 'Last 7 days', aiOutput: '**Completion Rate Analysis**\n\n**Strong performance:** 65% average is great!\n\n**Patterns:**\n- 90% video: Short, punchy, pattern interrupts\n- 30% video: Slow intro, too long\n\n**Recommendations:**\n1. Keep videos under 30 seconds initially\n2. Hook in first 1 second\n3. Use text overlays for retention' },
      { platform: 'YouTube', metricType: 'Revenue', dataInput: 'RPM: $4.50, Total revenue: $2250, Highest RPM video: $8.00', timeframe: 'Last 30 days', aiOutput: '**Revenue Analysis**\n\n**Earnings:** $2250/month at $4.50 RPM\n\n**Insights:**\n- Finance/tech content gets higher RPM\n- Longer watch time = better RPM\n\n**Recommendations:**\n1. Create more high-RPM topic content\n2. Increase video length for more ad slots\n3. Consider membership/sponsorships' },
      { platform: 'Instagram', metricType: 'Profile Visits', dataInput: 'Profile visits: 10K, Link clicks: 500, Bio link CTR: 5%', timeframe: 'Last 7 days', aiOutput: '**Profile Traffic Analysis**\n\n**Bio link CTR:** 5% is average\n\n**Improvements:**\n- Clearer CTA in bio\n- Update link regularly\n- Reference link in content\n\n**Recommendations:**\n1. Use link-in-bio tool\n2. Add link CTA in captions\n3. Update bio weekly' },
      { platform: 'TikTok', metricType: 'Profile Views', dataInput: 'Profile views: 25K, Follow rate: 8%', timeframe: 'Last 7 days', aiOutput: '**Profile Conversion Analysis**\n\n**Follow rate:** 8% is solid!\n\n**Optimization:**\n- Bio is working but could improve\n- Profile video should hook viewers\n\n**Recommendations:**\n1. Create a strong pinned video\n2. Use bio to establish credibility\n3. Add clear content promise' },
      { platform: 'YouTube', metricType: 'Comments', dataInput: 'Avg comments: 200, Response rate: 50%, Sentiment: 85% positive', timeframe: 'Last 30 days', aiOutput: '**Comment Analysis**\n\n**Engagement:** Good comment volume!\n\n**Areas to improve:**\n- Increase response rate to 80%+\n- Address negative comments professionally\n\n**Recommendations:**\n1. Pin best comments\n2. Ask specific questions\n3. Heart all comments in first hour' },
      { platform: 'Instagram', metricType: 'Saves', dataInput: 'Avg saves: 500, Best: 2000, Save rate: 3%', timeframe: 'Last 7 days', aiOutput: '**Saves Analysis**\n\n**Strong indicator:** Saves show valuable content!\n\n**Patterns:**\n- Educational posts get most saves\n- Carousel posts perform well\n\n**Recommendations:**\n1. Create more saveable content\n2. Add "Save this for later"\n3. Use carousels for tutorials' },
      { platform: 'YouTube', metricType: 'Traffic Sources', dataInput: 'Browse: 40%, Search: 30%, Suggested: 20%, External: 10%', timeframe: 'Last 30 days', aiOutput: '**Traffic Source Analysis**\n\n**Healthy mix!** Good distribution\n\n**Optimization:**\n- Search traffic can be increased\n- Suggested videos is growth opportunity\n\n**Recommendations:**\n1. SEO optimize titles/descriptions\n2. Create series for suggested\n3. Promote on social for external' },
    ];

    await Analytics.bulkCreate(analyticsData.map(item => ({ ...item, userId })));
    console.log('✅ Analytics seeded');

    // Seed Competitors (15+ items)
    const competitorsData = [
      { competitorName: 'TechChannel', competitorUrl: 'youtube.com/techchannel', platform: 'YouTube', analysisType: 'Content strategy', aiOutput: '**Competitor Analysis: TechChannel**\n\n**Content Strategy:**\n- Posts 3x/week consistently\n- Mix of reviews, tutorials, news\n- High production value\n\n**Strengths:**\n- Strong SEO titles\n- Engaging thumbnails\n- Active community\n\n**Opportunities:**\n- Less consistent on shorts\n- Slower to cover news\n- Could improve engagement' },
      { competitorName: 'FitLife', competitorUrl: 'tiktok.com/@fitlife', platform: 'TikTok', analysisType: 'Engagement analysis', aiOutput: '**Competitor Analysis: FitLife**\n\n**Engagement Metrics:**\n- Avg likes: 50K\n- Comment rate: 2%\n- Share rate: 1.5%\n\n**Strengths:**\n- Consistent posting\n- Trending sound usage\n- Relatable content\n\n**Opportunities:**\n- Less educational content\n- Could improve hooks\n- Missing collab opportunities' },
      { competitorName: 'CookWithMe', competitorUrl: 'youtube.com/cookwithme', platform: 'YouTube', analysisType: 'Content gaps', aiOutput: '**Competitor Analysis: CookWithMe**\n\n**Content Gaps Identified:**\n- No budget cooking content\n- Missing meal prep videos\n- Limited cultural cuisine variety\n\n**Your Opportunity:**\n- Budget-friendly recipes niche\n- Quick weeknight meals\n- International cuisine fusion\n\n**Action Items:**\n1. Create budget cooking series\n2. Target "quick recipes" keywords\n3. Collaborate with food brands' },
      { competitorName: 'BeautyGuru', competitorUrl: 'instagram.com/beautyguru', platform: 'Instagram', analysisType: 'Posting strategy', aiOutput: '**Competitor Analysis: BeautyGuru**\n\n**Posting Schedule:**\n- Feed posts: 5x/week\n- Reels: 2x/day\n- Stories: 10+/day\n\n**Content Mix:**\n- 40% tutorials\n- 30% reviews\n- 20% GRWM\n- 10% personal\n\n**Learnings:**\n- Reels drive most growth\n- Stories maintain engagement\n- Tutorials get most saves' },
      { competitorName: 'GamePro', competitorUrl: 'youtube.com/gamepro', platform: 'YouTube', analysisType: 'Growth strategy', aiOutput: '**Competitor Analysis: GamePro**\n\n**Growth Tactics:**\n- New release coverage\n- Stream highlights\n- Community events\n\n**Growth Rate:** +50K subs/month\n\n**Key Strategies:**\n- First to post on new games\n- Strong Discord community\n- Regular collaborations\n\n**Your Differentiation:**\n- Focus on indie games\n- Deeper game analysis\n- Unique editing style' },
      { competitorName: 'MoneyTalks', competitorUrl: 'tiktok.com/@moneytalks', platform: 'TikTok', analysisType: 'Content format', aiOutput: '**Competitor Analysis: MoneyTalks**\n\n**Content Formats:**\n- Quick tips (15-30s): 60%\n- Storytime (60s+): 25%\n- Greenscreen: 15%\n\n**What Works:**\n- Numbered lists\n- Text overlays\n- Trending sounds\n\n**Your Opportunity:**\n- More in-depth content\n- Personal finance stories\n- Interactive content' },
      { competitorName: 'TravelDiary', competitorUrl: 'youtube.com/traveldiary', platform: 'YouTube', analysisType: 'Production quality', aiOutput: '**Competitor Analysis: TravelDiary**\n\n**Production Quality:**\n- 4K footage\n- Professional color grading\n- Cinematic b-roll\n- Licensed music\n\n**Equipment:**\n- Sony A7IV\n- DJI drone\n- Gimbal\n\n**Your Approach:**\n- Match quality where possible\n- Focus on authentic storytelling\n- Unique destinations' },
      { competitorName: 'StyleIcon', competitorUrl: 'instagram.com/styleicon', platform: 'Instagram', analysisType: 'Brand partnerships', aiOutput: '**Competitor Analysis: StyleIcon**\n\n**Brand Partnerships:**\n- Works with: Zara, H&M, Revolve\n- Avg partnership: 2/month\n- Mix of paid and gifted\n\n**Pricing Estimate:**\n- Feed post: $2-5K\n- Reel: $5-10K\n- Story: $500-1K\n\n**Your Strategy:**\n- Start with smaller brands\n- Build portfolio\n- Focus on alignment' },
      { competitorName: 'StudyTips', competitorUrl: 'tiktok.com/@studytips', platform: 'TikTok', analysisType: 'Viral content', aiOutput: '**Competitor Analysis: StudyTips**\n\n**Viral Content Patterns:**\n- "Things I wish I knew" format\n- Relatable student moments\n- Study aesthetic content\n\n**Viral Hits:**\n- 1M+ views on study routines\n- High saves on tip content\n- Duets perform well\n\n**Replicate:**\n- Use similar formats\n- Add your unique perspective\n- Jump on trending sounds' },
      { competitorName: 'DIYKing', competitorUrl: 'youtube.com/diyking', platform: 'YouTube', analysisType: 'Thumbnail strategy', aiOutput: '**Competitor Analysis: DIYKing**\n\n**Thumbnail Style:**\n- Before/after splits\n- Bright, high contrast\n- Faces with expressions\n- Bold text overlay\n\n**CTR Indicators:**\n- Clear transformation shown\n- Curiosity gap in text\n- Consistent branding\n\n**Apply:**\n- Use similar composition\n- Test bright backgrounds\n- Add your brand colors' },
      { competitorName: 'PetLife', competitorUrl: 'tiktok.com/@petlife', platform: 'TikTok', analysisType: 'Audience engagement', aiOutput: '**Competitor Analysis: PetLife**\n\n**Engagement Tactics:**\n- Reply to every comment\n- Ask questions in captions\n- User-generated content features\n\n**Community Building:**\n- Pet name hashtag\n- Weekly challenges\n- Fan art features\n\n**Your Strategy:**\n- Create community hashtag\n- Regular Q&A content\n- Feature follower pets' },
      { competitorName: 'MotivateMe', competitorUrl: 'youtube.com/motivateme', platform: 'YouTube', analysisType: 'Content calendar', aiOutput: '**Competitor Analysis: MotivateMe**\n\n**Content Calendar:**\n- Sunday: Weekly motivation\n- Tuesday: Success stories\n- Thursday: Practical tips\n\n**Seasonal Content:**\n- New Year goal setting\n- Back to school motivation\n- Year-end reflection\n\n**Your Calendar:**\n- Find unique posting days\n- Create signature series\n- Plan seasonal content early' },
      { competitorName: 'MusicVibes', competitorUrl: 'youtube.com/musicvibes', platform: 'YouTube', analysisType: 'Revenue streams', aiOutput: '**Competitor Analysis: MusicVibes**\n\n**Revenue Streams:**\n- AdSense: 40%\n- Sponsorships: 30%\n- Merch: 15%\n- Courses: 15%\n\n**Monetization:**\n- Instrument reviews (affiliate)\n- Production courses\n- Sample pack sales\n\n**Your Opportunities:**\n- Create digital products\n- Offer lessons\n- Build affiliate partnerships' },
      { competitorName: 'HomeDecorPro', competitorUrl: 'instagram.com/homedecorpro', platform: 'Instagram', analysisType: 'Hashtag strategy', aiOutput: '**Competitor Analysis: HomeDecorPro**\n\n**Hashtag Strategy:**\n- Uses 25-30 hashtags\n- Mix of sizes (small to large)\n- Niche + broad mix\n\n**Top Hashtags:**\n#homedecor #interiordesign #homeinspo #decorating #homedesign\n\n**Your Strategy:**\n- Research niche hashtags\n- Create branded hashtag\n- Rotate hashtag groups' },
      { competitorName: 'WellnessJourney', competitorUrl: 'youtube.com/wellnessjourney', platform: 'YouTube', analysisType: 'Community building', aiOutput: '**Competitor Analysis: WellnessJourney**\n\n**Community Features:**\n- Active Discord server\n- Monthly challenges\n- Member spotlights\n- Live Q&As\n\n**Engagement:**\n- 80% comment response rate\n- Community tab active daily\n- Polls for content ideas\n\n**Your Approach:**\n- Start Discord/community\n- Regular live streams\n- Feature community members' },
    ];

    await Competitor.bulkCreate(competitorsData.map(item => ({ ...item, userId })));
    console.log('✅ Competitors seeded');

    // Seed Personas (15+ items)
    const personasData = [
      { niche: 'Technology', platform: 'YouTube', demographics: 'Male, 25-34, urban, employed', interests: 'Gadgets, programming, gaming', aiOutput: '**Audience Persona: Tech Tom**\n\n**Demographics:**\n- Age: 28\n- Gender: Male\n- Location: Urban city\n- Income: $60-90K\n- Education: Bachelor\'s degree\n\n**Psychographics:**\n- Early adopter\n- Value-conscious but willing to pay for quality\n- Research-heavy before purchases\n\n**Pain Points:**\n- Too many options\n- Time to research\n- FOMO on new tech\n\n**Content Preferences:**\n- In-depth reviews\n- Comparisons\n- Honest opinions' },
      { niche: 'Fitness', platform: 'TikTok', demographics: 'Female, 18-28, active lifestyle', interests: 'Workouts, nutrition, wellness', aiOutput: '**Audience Persona: Fitness Fiona**\n\n**Demographics:**\n- Age: 24\n- Gender: Female\n- Location: Suburban\n- Income: $35-55K\n\n**Psychographics:**\n- Health-conscious\n- Socially motivated\n- Progress-focused\n\n**Pain Points:**\n- Time constraints\n- Gym intimidation\n- Conflicting advice\n\n**Content Preferences:**\n- Quick workouts\n- Before/after results\n- Relatable struggles' },
      { niche: 'Cooking', platform: 'YouTube', demographics: 'Mixed, 30-45, families', interests: 'Recipes, meal planning, kitchen tips', aiOutput: '**Audience Persona: Cooking Carla**\n\n**Demographics:**\n- Age: 35\n- Gender: Female (60%)\n- Location: Suburban\n- Family: Has kids\n\n**Psychographics:**\n- Time-strapped\n- Budget-conscious\n- Health-aware\n\n**Pain Points:**\n- "What\'s for dinner?"\n- Picky eaters\n- Limited time\n\n**Content Preferences:**\n- Quick recipes\n- Budget meals\n- Kid-friendly options' },
      { niche: 'Beauty', platform: 'Instagram', demographics: 'Female, 16-30, trend-conscious', interests: 'Makeup, skincare, fashion', aiOutput: '**Audience Persona: Beauty Bella**\n\n**Demographics:**\n- Age: 22\n- Gender: Female\n- Location: Urban\n- Student/Early career\n\n**Psychographics:**\n- Trend-aware\n- Brand-loyal\n- Social proof driven\n\n**Pain Points:**\n- Product overload\n- Budget limits\n- Finding what works\n\n**Content Preferences:**\n- Tutorials\n- Honest reviews\n- Drugstore dupes' },
      { niche: 'Gaming', platform: 'YouTube', demographics: 'Male, 16-28, students/young professionals', interests: 'Video games, esports, streaming', aiOutput: '**Audience Persona: Gamer Gary**\n\n**Demographics:**\n- Age: 20\n- Gender: Male (75%)\n- Location: Global\n- Student/Part-time work\n\n**Psychographics:**\n- Community-oriented\n- Competitive\n- Entertainment-focused\n\n**Pain Points:**\n- Game selection\n- Building skills\n- Finding gaming friends\n\n**Content Preferences:**\n- Gameplay\n- Reviews\n- Tips and tricks' },
      { niche: 'Finance', platform: 'TikTok', demographics: 'Mixed, 22-35, working professionals', interests: 'Investing, budgeting, side hustles', aiOutput: '**Audience Persona: Finance Freddie**\n\n**Demographics:**\n- Age: 27\n- Gender: Mixed\n- Location: Urban\n- Income: $40-80K\n\n**Psychographics:**\n- Future-oriented\n- Anxiety about money\n- Wants simplicity\n\n**Pain Points:**\n- Financial overwhelm\n- Where to start\n- Trust issues with advice\n\n**Content Preferences:**\n- Simple explanations\n- Actionable steps\n- Real results' },
      { niche: 'Travel', platform: 'YouTube', demographics: 'Mixed, 25-40, adventure seekers', interests: 'Travel, photography, experiences', aiOutput: '**Audience Persona: Travel Taylor**\n\n**Demographics:**\n- Age: 30\n- Gender: Mixed\n- Location: Urban\n- Income: $50-100K\n\n**Psychographics:**\n- Experience-driven\n- Instagram-aware\n- Planning-oriented\n\n**Pain Points:**\n- Trip planning stress\n- Budget concerns\n- Hidden gems finding\n\n**Content Preferences:**\n- Destination guides\n- Budget tips\n- Authentic experiences' },
      { niche: 'Lifestyle', platform: 'YouTube', demographics: 'Female, 20-35, aspirational', interests: 'Home, wellness, productivity', aiOutput: '**Audience Persona: Lifestyle Lily**\n\n**Demographics:**\n- Age: 26\n- Gender: Female\n- Location: Urban/Suburban\n- Income: $40-70K\n\n**Psychographics:**\n- Self-improvement focused\n- Aesthetic-driven\n- Routine-loving\n\n**Pain Points:**\n- Work-life balance\n- Organization\n- Feeling behind\n\n**Content Preferences:**\n- Routines\n- Organization\n- Day in life' },
      { niche: 'Education', platform: 'YouTube', demographics: 'Mixed, 16-25, students', interests: 'Learning, productivity, career', aiOutput: '**Audience Persona: Student Sam**\n\n**Demographics:**\n- Age: 19\n- Gender: Mixed\n- Location: Global\n- Student\n\n**Psychographics:**\n- Achievement-oriented\n- Stressed\n- Future-focused\n\n**Pain Points:**\n- Study effectiveness\n- Time management\n- Exam anxiety\n\n**Content Preferences:**\n- Study tips\n- Motivation\n- Real experiences' },
      { niche: 'Fashion', platform: 'Instagram', demographics: 'Female, 18-35, style-conscious', interests: 'Fashion, shopping, trends', aiOutput: '**Audience Persona: Fashion Frankie**\n\n**Demographics:**\n- Age: 25\n- Gender: Female (80%)\n- Location: Urban\n- Disposable income for fashion\n\n**Psychographics:**\n- Trend-aware\n- Sustainability-conscious\n- Expressive through style\n\n**Pain Points:**\n- Trend overload\n- Budget vs. style\n- Sustainable options\n\n**Content Preferences:**\n- Outfit ideas\n- Styling tips\n- Shopping guides' },
      { niche: 'Music', platform: 'YouTube', demographics: 'Mixed, 16-35, music enthusiasts', interests: 'Music, instruments, production', aiOutput: '**Audience Persona: Music Mike**\n\n**Demographics:**\n- Age: 22\n- Gender: Mixed\n- Location: Global\n- Some musical background\n\n**Psychographics:**\n- Creative\n- Passionate\n- Aspiring musician\n\n**Pain Points:**\n- Learning curve\n- Equipment costs\n- Standing out\n\n**Content Preferences:**\n- Covers\n- Tutorials\n- Behind the scenes' },
      { niche: 'Pet content', platform: 'TikTok', demographics: 'Mixed, 18-45, pet owners', interests: 'Pets, animals, pet care', aiOutput: '**Audience Persona: Pet Parent Pat**\n\n**Demographics:**\n- Age: 30\n- Gender: Mixed\n- Location: Suburban\n- Pet owner\n\n**Psychographics:**\n- Treats pets as family\n- Seeks community\n- Product-curious\n\n**Pain Points:**\n- Pet behavior\n- Finding good products\n- Pet health info\n\n**Content Preferences:**\n- Cute/funny content\n- Product reviews\n- Training tips' },
      { niche: 'DIY/Crafts', platform: 'Pinterest', demographics: 'Female, 25-45, homeowners', interests: 'Home decor, crafts, organization', aiOutput: '**Audience Persona: DIY Diana**\n\n**Demographics:**\n- Age: 35\n- Gender: Female (85%)\n- Location: Suburban\n- Homeowner\n\n**Psychographics:**\n- Creative\n- Budget-conscious\n- Satisfaction from making\n\n**Pain Points:**\n- Project complexity\n- Time investment\n- Tool requirements\n\n**Content Preferences:**\n- Step-by-step tutorials\n- Before/after\n- Budget-friendly' },
      { niche: 'Health', platform: 'YouTube', demographics: 'Mixed, 30-50, health-focused', interests: 'Wellness, nutrition, fitness', aiOutput: '**Audience Persona: Health Hannah**\n\n**Demographics:**\n- Age: 38\n- Gender: Mixed\n- Location: Urban/Suburban\n- Middle income\n\n**Psychographics:**\n- Prevention-focused\n- Research-oriented\n- Holistic approach\n\n**Pain Points:**\n- Conflicting info\n- Sustainable habits\n- Time for self-care\n\n**Content Preferences:**\n- Evidence-based\n- Practical tips\n- Real talk' },
      { niche: 'Motivation', platform: 'YouTube', demographics: 'Mixed, 18-40, ambitious', interests: 'Self-improvement, success, mindset', aiOutput: '**Audience Persona: Motivated Max**\n\n**Demographics:**\n- Age: 28\n- Gender: Mixed\n- Location: Global\n- Ambitious professional\n\n**Psychographics:**\n- Growth mindset\n- Goal-oriented\n- Action-taker\n\n**Pain Points:**\n- Staying motivated\n- Overcoming setbacks\n- Finding direction\n\n**Content Preferences:**\n- Success stories\n- Practical advice\n- Authentic struggles' },
    ];

    await Persona.bulkCreate(personasData.map(item => ({ ...item, userId })));
    console.log('✅ Personas seeded');

    // Seed Repurpose (15+ items)
    const repurposeData = [
      { originalContent: 'Full 20-minute YouTube tutorial on morning routines', sourcePlatform: 'YouTube', targetPlatform: 'TikTok', contentType: 'Tutorial', aiOutput: '**Repurposed Content for TikTok:**\n\n**Clip 1 (60s):** Best morning routine tip - the 1-minute rule\n**Clip 2 (30s):** Morning routine mistakes (hook: "Stop doing this!")\n**Clip 3 (45s):** My 5 AM wake-up secret\n\n**Format:**\n- Vertical video\n- Fast-paced edits\n- Text overlays\n- Trending sound if applicable\n\n**Captions:**\n"This one habit changed my mornings #morningroutine #productivity #fyp"' },
      { originalContent: '10-minute product review video', sourcePlatform: 'YouTube', targetPlatform: 'Instagram Reels', contentType: 'Review', aiOutput: '**Repurposed for Instagram Reels:**\n\n**Reel 1 (30s):** Quick verdict + key features\n**Reel 2 (60s):** Pros and cons breakdown\n**Reel 3 (30s):** "Watch before you buy" hook\n\n**Format:**\n- 9:16 aspect ratio\n- Captions on screen\n- Clear CTA at end\n\n**Caption:**\n"Honest review: Is [product] worth it? Full video on YouTube!"' },
      { originalContent: 'Behind-the-scenes vlog (15 min)', sourcePlatform: 'YouTube', targetPlatform: 'TikTok', contentType: 'Vlog', aiOutput: '**Repurposed for TikTok:**\n\n**Clip 1:** "POV: Day in my life as a creator"\n**Clip 2:** "The part of content creation nobody shows"\n**Clip 3:** Funny blooper compilation\n\n**Format:**\n- Raw, authentic clips\n- Trending sounds\n- Relatable hooks\n\n**Caption:**\n"Creator life isn\'t always glamorous #contentcreator #bts"' },
      { originalContent: 'Educational thread about investing', sourcePlatform: 'Twitter', targetPlatform: 'TikTok', contentType: 'Educational', aiOutput: '**Repurposed for TikTok:**\n\n**Format:** Talking head with text overlays\n\n**Script:**\n"Here are 5 investing mistakes I made so you don\'t have to:\n1. [point + visual]\n2. [point + visual]..."\n\n**Style:**\n- Greenscreen with graphics\n- Each point = 10-15 seconds\n- Save/share CTA\n\n**Caption:**\n"Wish I knew this earlier #investing #moneytok #financialliteracy"' },
      { originalContent: 'Long-form blog post about productivity', sourcePlatform: 'Blog', targetPlatform: 'Instagram Carousel', contentType: 'Article', aiOutput: '**Repurposed for Instagram Carousel:**\n\n**Slide 1:** Hook title "7 Productivity Habits That Changed My Life"\n**Slides 2-8:** One habit per slide with visual\n**Slide 9:** Summary + CTA\n\n**Design:**\n- Consistent branding\n- Easy-to-read fonts\n- Swipe prompts\n\n**Caption:**\n"Save this for your next productive week! Which one will you try first? [Full article link in bio]"' },
      { originalContent: 'Podcast episode (45 min interview)', sourcePlatform: 'Podcast', targetPlatform: 'YouTube', contentType: 'Interview', aiOutput: '**Repurposed for YouTube:**\n\n**Full video:** Podcast with video recording\n**Shorts/Clips:**\n- Best quote moments (60s each)\n- Controversial takes\n- Practical tips\n\n**Enhancements:**\n- Add visual elements\n- Chapter markers\n- Animated captions\n\n**Title:** "[Guest Name] on [Topic] | Full Interview"\n**Shorts:** "The advice that changed [Guest]\'s career"' },
      { originalContent: 'Instagram Reel viral dance/trend', sourcePlatform: 'Instagram', targetPlatform: 'YouTube Shorts', contentType: 'Trend', aiOutput: '**Repurposed for YouTube Shorts:**\n\n**Direct repost:**\n- Add YouTube-specific text\n- Adjust caption for YouTube audience\n- Include channel subscribe CTA\n\n**Extended version:**\n- Behind-the-scenes of creating the Reel\n- Tutorial on the trend\n\n**Caption/Title:**\n"I tried the [trend] #shorts #viral"' },
      { originalContent: 'How-to guide (20 min tutorial)', sourcePlatform: 'YouTube', targetPlatform: 'LinkedIn', contentType: 'Tutorial', aiOutput: '**Repurposed for LinkedIn:**\n\n**Format 1: Text Post**\n"5 key takeaways from my new tutorial on [topic]:\n\n1. [Insight]\n2. [Insight]\n3. [Insight]\n4. [Insight]\n5. [Insight]\n\nFull tutorial: [link]\n\nWhat would you add? Comment below!"\n\n**Format 2: Video Clip**\n- 2-3 minute highlight reel\n- Professional tone\n- Add captions' },
      { originalContent: 'Recipe video (10 min)', sourcePlatform: 'YouTube', targetPlatform: 'Pinterest', contentType: 'Recipe', aiOutput: '**Repurposed for Pinterest:**\n\n**Pin 1:** Recipe infographic (vertical)\n**Pin 2:** Step-by-step process shots\n**Pin 3:** Final dish with recipe card\n\n**Format:**\n- 2:3 aspect ratio\n- Text overlay with recipe name\n- Clear, bright food photography\n\n**Description:**\n"Easy [Recipe Name] - ready in 30 minutes! This delicious meal is perfect for [occasion]. Get the full recipe with video tutorial. #recipes #cooking #food"' },
      { originalContent: 'Motivational speech (5 min)', sourcePlatform: 'YouTube', targetPlatform: 'Instagram', contentType: 'Motivational', aiOutput: '**Repurposed for Instagram:**\n\n**Reel 1 (60s):** Most powerful 60 seconds\n**Reel 2 (30s):** Key quote with visuals\n**Carousel:** Quote graphics with speech excerpts\n\n**Format:**\n- Dramatic music\n- Captions for sound-off\n- Emotional pacing\n\n**Caption:**\n"The reminder you needed today. Save this. [Full speech link in bio] #motivation #inspiration #mindset"' },
      { originalContent: 'Q&A session (30 min)', sourcePlatform: 'YouTube Live', targetPlatform: 'TikTok', contentType: 'Q&A', aiOutput: '**Repurposed for TikTok:**\n\n**Format:** Question + Answer clips\n\n**Clip structure:**\n- Show question on screen\n- Your answer (30-60s)\n- Engaging hook\n\n**Series:** "Answering your questions" series\n\n**Caption:**\n"You asked, I answered! Part 1 #qanda #[niche]tok"' },
      { originalContent: 'Transformation story (personal journey)', sourcePlatform: 'YouTube', targetPlatform: 'Twitter Thread', contentType: 'Story', aiOutput: '**Repurposed for Twitter/X Thread:**\n\n**Thread structure:**\n\n1/ Hook: "2 years ago, I [starting point]. Today, I [achievement]. Here\'s what I learned: (thread)"\n\n2/ The beginning - where I started\n\n3/ The turning point\n\n4/ The struggle\n\n5/ The breakthrough\n\n6/ Key lessons\n\n7/ Call to action\n\n**Tips:**\n- Number each tweet\n- Include images/screenshots\n- End with engagement question' },
      { originalContent: 'Workout routine (20 min)', sourcePlatform: 'YouTube', targetPlatform: 'Instagram Stories', contentType: 'Fitness', aiOutput: '**Repurposed for Instagram Stories:**\n\n**Story series:**\n1. "New workout alert" intro\n2-6. One exercise per story (10s each)\n7. Full workout available (swipe up/link)\n\n**Format:**\n- 15-second clips max\n- Text overlay with reps\n- Music overlay\n- "Tap to pause" for instructions\n\n**Highlight:** Save to "Workouts" highlight' },
      { originalContent: 'Product comparison (15 min)', sourcePlatform: 'YouTube', targetPlatform: 'Email Newsletter', contentType: 'Review', aiOutput: '**Repurposed for Email Newsletter:**\n\n**Subject:** "[Product A] vs [Product B] - My Honest Take"\n\n**Content:**\n- Summary of key differences\n- Winner for different use cases\n- Embedded video clip\n- Link to full video\n\n**Format:**\n- Bullet points\n- Comparison table\n- Clear recommendation\n\n**CTA:** "Watch the full breakdown on YouTube"' },
      { originalContent: 'Day in my life vlog (15 min)', sourcePlatform: 'YouTube', targetPlatform: 'BeReal/Casual Platforms', contentType: 'Lifestyle', aiOutput: '**Repurposed for Casual Platforms:**\n\n**BeReal-style content:**\n- Screenshot key moments\n- "What my vlog doesn\'t show" authentic moments\n\n**TikTok "Photo dump" trend:**\n- Collection of vlog screenshots\n- Trending sound\n- Casual, authentic vibe\n\n**Caption:**\n"What filming a YouTube video actually looks like vs the final product"' },
    ];

    await Repurpose.bulkCreate(repurposeData.map(item => ({ ...item, userId })));
    console.log('✅ Repurpose data seeded');

    console.log('\n🎉 Database seeding completed successfully!');
    console.log('\n📝 Demo credentials:');
    console.log('   Email: demo@creator.ai');
    console.log('   Password: demo123');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
